import { PrismaClient, DifficultyLevel } from '@prisma/client';

const prisma = new PrismaClient();

const questions = [
  // ============ UNI - INGENIERÍA ============
  // Matemática - UNI
  {
    id: 'q-uni-mat-001',
    text: 'Si log₂(x) = 5, ¿cuál es el valor de x?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-sistemas',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'log₂(x) = 5 → x = 2⁵ = 32',
    options: [
      { text: '10', isCorrect: false, orderIndex: 0 },
      { text: '25', isCorrect: false, orderIndex: 1 },
      { text: '32', isCorrect: true, orderIndex: 2 },
      { text: '64', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-002',
    text: '¿Cuál es la derivada de f(x) = 3x² + 2x - 5?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-civil',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: "f'(x) = 6x + 2 usando la regla de la potencia",
    options: [
      { text: '6x + 2', isCorrect: true, orderIndex: 0 },
      { text: '3x + 2', isCorrect: false, orderIndex: 1 },
      { text: '6x² + 2', isCorrect: false, orderIndex: 2 },
      { text: '6x - 5', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-003',
    text: 'Resolver: |x - 3| = 7',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: '|x-3|=7 → x-3=7 o x-3=-7 → x=10 o x=-4',
    options: [
      { text: 'x = 10', isCorrect: false, orderIndex: 0 },
      { text: 'x = -4', isCorrect: false, orderIndex: 1 },
      { text: 'x = 10 o x = -4', isCorrect: true, orderIndex: 2 },
      { text: 'x = 4', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-004',
    text: '¿Cuánto vale el determinante de la matriz [[2,1],[3,4]]?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-sistemas',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: 'det = (2)(4) - (1)(3) = 8 - 3 = 5',
    options: [
      { text: '5', isCorrect: true, orderIndex: 0 },
      { text: '11', isCorrect: false, orderIndex: 1 },
      { text: '7', isCorrect: false, orderIndex: 2 },
      { text: '-5', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-005',
    text: 'Si f(x) = e^x, ¿cuál es su derivada?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-electronica',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: "La derivada de e^x es e^x (propiedad fundamental)",
    options: [
      { text: 'e^x', isCorrect: true, orderIndex: 0 },
      { text: 'x·e^(x-1)', isCorrect: false, orderIndex: 1 },
      { text: 'ln(x)', isCorrect: false, orderIndex: 2 },
      { text: 'e^(x+1)', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-006',
    text: 'Calcular: ∫₀² x² dx',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-civil',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: '∫x²dx = x³/3. Evaluando de 0 a 2: (8/3) - (0) = 8/3',
    options: [
      { text: '8/3', isCorrect: true, orderIndex: 0 },
      { text: '4', isCorrect: false, orderIndex: 1 },
      { text: '2', isCorrect: false, orderIndex: 2 },
      { text: '16/3', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-007',
    text: '¿Cuál es el conjunto solución de x² - 5x + 6 = 0?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-mecanica',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Factorizando: (x-2)(x-3)=0 → x=2 o x=3',
    options: [
      { text: '{2, 3}', isCorrect: true, orderIndex: 0 },
      { text: '{1, 6}', isCorrect: false, orderIndex: 1 },
      { text: '{−2, −3}', isCorrect: false, orderIndex: 2 },
      { text: '{5, 6}', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-008',
    text: 'Calcular el MCM de 12 y 18.',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: '12=2²·3, 18=2·3² → MCM = 2²·3² = 36',
    options: [
      { text: '36', isCorrect: true, orderIndex: 0 },
      { text: '72', isCorrect: false, orderIndex: 1 },
      { text: '6', isCorrect: false, orderIndex: 2 },
      { text: '216', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-009',
    text: '¿Cuál es la suma de los primeros 10 números naturales?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-sistemas',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'S = n(n+1)/2 = 10(11)/2 = 55',
    options: [
      { text: '55', isCorrect: true, orderIndex: 0 },
      { text: '45', isCorrect: false, orderIndex: 1 },
      { text: '110', isCorrect: false, orderIndex: 2 },
      { text: '100', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-010',
    text: 'Hallar la ecuación de la recta que pasa por (2,3) y (4,7).',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-civil',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'm = (7-3)/(4-2) = 2. y - 3 = 2(x-2) → y = 2x - 1',
    options: [
      { text: 'y = 2x - 1', isCorrect: true, orderIndex: 0 },
      { text: 'y = x + 1', isCorrect: false, orderIndex: 1 },
      { text: 'y = 2x + 1', isCorrect: false, orderIndex: 2 },
      { text: 'y = 2x - 3', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-011',
    text: '¿Cuánto es 2³ + 3²?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-electronica',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: '2³ + 3² = 8 + 9 = 17',
    options: [
      { text: '17', isCorrect: true, orderIndex: 0 },
      { text: '11', isCorrect: false, orderIndex: 1 },
      { text: '25', isCorrect: false, orderIndex: 2 },
      { text: '19', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-mat-012',
    text: '¿Cuál es el valor de π (pi) aproximado a 2 decimales?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-mecanica',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'π ≈ 3.14159... ≈ 3.14 a dos decimales',
    options: [
      { text: '3.14', isCorrect: true, orderIndex: 0 },
      { text: '3.16', isCorrect: false, orderIndex: 1 },
      { text: '3.41', isCorrect: false, orderIndex: 2 },
      { text: '3.12', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Física - UNI
  {
    id: 'q-uni-fis-001',
    text: '¿Qué relación hay entre fuerza, masa y aceleración según Newton?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-civil',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'F = m · a (Segunda Ley de Newton)',
    options: [
      { text: 'F = ma', isCorrect: true, orderIndex: 0 },
      { text: 'F = m/a', isCorrect: false, orderIndex: 1 },
      { text: 'F = m + a', isCorrect: false, orderIndex: 2 },
      { text: 'F = m - a', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-002',
    text: 'Un cuerpo cae libremente desde 80m. ¿Cuánto tiempo tarda en llegar al suelo? (g=10m/s²)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-mecanica',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'h = ½gt² → 80 = ½(10)t² → t² = 16 → t = 4s',
    options: [
      { text: '4 s', isCorrect: true, orderIndex: 0 },
      { text: '8 s', isCorrect: false, orderIndex: 1 },
      { text: '2 s', isCorrect: false, orderIndex: 2 },
      { text: '16 s', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-003',
    text: '¿Cuál es la energía cinética de un objeto de 2kg a 5m/s?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-electronica',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Ec = ½mv² = ½(2)(25) = 25 J',
    options: [
      { text: '25 J', isCorrect: true, orderIndex: 0 },
      { text: '10 J', isCorrect: false, orderIndex: 1 },
      { text: '50 J', isCorrect: false, orderIndex: 2 },
      { text: '20 J', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-004',
    text: '¿Cuántos electrones hay en 1 coulomb de carga? (e = 1.6×10⁻¹⁹ C)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-electronica',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'n = Q/e = 1/(1.6×10⁻¹⁹) = 6.25×10¹⁸ electrones',
    options: [
      { text: '6.25×10¹⁸', isCorrect: true, orderIndex: 0 },
      { text: '1.6×10⁻¹⁹', isCorrect: false, orderIndex: 1 },
      { text: '1.6×10¹⁹', isCorrect: false, orderIndex: 2 },
      { text: '6.25×10⁻¹⁸', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-005',
    text: '¿A qué temperatura Celsius equivalen 98°F?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'C = (F-32)×5/9 = (98-32)×5/9 = 66×5/9 = 36.67°C',
    options: [
      { text: '36.7°C', isCorrect: true, orderIndex: 0 },
      { text: '32°C', isCorrect: false, orderIndex: 1 },
      { text: '45°C', isCorrect: false, orderIndex: 2 },
      { text: '30°C', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-006',
    text: '¿Qué tipo de onda es el sonido?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-mecanica',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: 'El sonido es una onda mecánica longitudinal.',
    options: [
      { text: 'Mecánica longitudinal', isCorrect: true, orderIndex: 0 },
      { text: 'Electromagnética', isCorrect: false, orderIndex: 1 },
      { text: 'Transversal', isCorrect: false, orderIndex: 2 },
      { text: 'Estacionaria', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-007',
    text: '¿Cuál es la presión en el fondo de un recipiente con 20m de agua? (ρ=1000kg/m³, g=10m/s²)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-civil',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'P = ρgh = 1000×10×20 = 200,000 Pa = 200 kPa',
    options: [
      { text: '200 kPa', isCorrect: true, orderIndex: 0 },
      { text: '100 kPa', isCorrect: false, orderIndex: 1 },
      { text: '20 kPa', isCorrect: false, orderIndex: 2 },
      { text: '2 kPa', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-fis-008',
    text: '¿Cuál es la frecuencia de un péndulo simple con período de 2s?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-mecanica',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: 'f = 1/T = 1/2 = 0.5 Hz',
    options: [
      { text: '0.5 Hz', isCorrect: true, orderIndex: 0 },
      { text: '2 Hz', isCorrect: false, orderIndex: 1 },
      { text: '1 Hz', isCorrect: false, orderIndex: 2 },
      { text: '4 Hz', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Química - UNI
  {
    id: 'q-uni-qui-001',
    text: '¿Cuál es el número atómico del oxígeno?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'El oxígeno tiene Z=8 (8 protones, 8 electrones).',
    options: [
      { text: '8', isCorrect: true, orderIndex: 0 },
      { text: '16', isCorrect: false, orderIndex: 1 },
      { text: '6', isCorrect: false, orderIndex: 2 },
      { text: '2', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-qui-002',
    text: '¿Qué tipo de reacción es: 2H₂ + O₂ → 2H₂O?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-quimica',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Dos sustancias (H₂ y O₂) forman una sola (H₂O): es una reacción de síntesis/combinación.',
    options: [
      { text: 'Síntesis (combinación)', isCorrect: true, orderIndex: 0 },
      { text: 'Descomposición', isCorrect: false, orderIndex: 1 },
      { text: 'Sustitución simple', isCorrect: false, orderIndex: 2 },
      { text: 'Neutralización', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-qui-003',
    text: '¿Cuántos moles hay en 36g de agua? (M(H₂O) = 18 g/mol)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'n = m/M = 36g / 18g/mol = 2 moles',
    options: [
      { text: '2 moles', isCorrect: true, orderIndex: 0 },
      { text: '1 mol', isCorrect: false, orderIndex: 1 },
      { text: '0.5 moles', isCorrect: false, orderIndex: 2 },
      { text: '18 moles', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-qui-004',
    text: '¿Cuál es la configuración electrónica del neón (Z=10)?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-quimica',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: 'Neón: 1s² 2s² 2p⁶ (10 electrones, configuración de gas noble)',
    options: [
      { text: '1s² 2s² 2p⁶', isCorrect: true, orderIndex: 0 },
      { text: '1s² 2s² 2p⁵', isCorrect: false, orderIndex: 1 },
      { text: '1s² 2s² 2p⁴', isCorrect: false, orderIndex: 2 },
      { text: '1s² 2s² 2p⁷', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-qui-005',
    text: '¿Qué representa el número de Avogadro?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: '6.022×10²³ entidades por mol de sustancia.',
    options: [
      { text: '6.022×10²³ partículas por mol', isCorrect: true, orderIndex: 0 },
      { text: 'La masa de 1 molécula', isCorrect: false, orderIndex: 1 },
      { text: 'El volumen de 1 mol', isCorrect: false, orderIndex: 2 },
      { text: 'La carga de 1 electrón', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Comunicación - UNI
  {
    id: 'q-uni-com-001',
    text: '¿Qué tipo de texto es una receta de cocina?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'comunicacion',
    careerId: 'ing-industrial',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Una receta de cocina es un texto instructivo/secuencial.',
    options: [
      { text: 'Instructivo', isCorrect: true, orderIndex: 0 },
      { text: 'Narrativo', isCorrect: false, orderIndex: 1 },
      { text: 'Descriptivo', isCorrect: false, orderIndex: 2 },
      { text: 'Argumentativo', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-com-002',
    text: '¿Qué figura retórica usa: "El tiempo es un río"?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'comunicacion',
    careerId: 'derecho',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Se compara el tiempo con un río: es una metáfora.',
    options: [
      { text: 'Metáfora', isCorrect: true, orderIndex: 0 },
      { text: 'Metonimia', isCorrect: false, orderIndex: 1 },
      { text: 'Hipérbole', isCorrect: false, orderIndex: 2 },
      { text: 'Comparación', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-com-003',
    text: '¿Cuál es la idea principal de un texto argumentativo?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'comunicacion',
    careerId: 'administracion',
    universityId: 'uni',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'Defender una tesis con argumentos lógicos y/rhetóricos.',
    options: [
      { text: 'Defender una tesis con argumentos', isCorrect: true, orderIndex: 0 },
      { text: 'Narrar eventos cronológicamente', isCorrect: false, orderIndex: 1 },
      { text: 'Describir situaciones sin opinión', isCorrect: false, orderIndex: 2 },
      { text: 'Explicar un proceso paso a paso', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Historia - UNI
  {
    id: 'q-uni-hist-001',
    text: '¿En qué año terminó la Segunda Guerra Mundial?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'historia',
    careerId: 'administracion',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'La WWII terminó en 1945 con la rendición de Alemania (mayo) y Japón (septiembre).',
    options: [
      { text: '1945', isCorrect: true, orderIndex: 0 },
      { text: '1944', isCorrect: false, orderIndex: 1 },
      { text: '1946', isCorrect: false, orderIndex: 2 },
      { text: '1943', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-uni-hist-002',
    text: '¿Quién fue el primer presidente del Perú independiente?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'historia',
    careerId: 'derecho',
    universityId: 'uni',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'José de San Martín nombró a José de la Riva-Agüero como primer presidente del Perú independiente en 1823.',
    options: [
      { text: 'José de la Riva-Agüero', isCorrect: true, orderIndex: 0 },
      { text: 'Simón Bolívar', isCorrect: false, orderIndex: 1 },
      { text: 'Andrés de Santa Cruz', isCorrect: false, orderIndex: 2 },
      { text: 'José de San Martín', isCorrect: false, orderIndex: 3 },
    ],
  },

  // ============ UNSAAC - CUSCO ============
  // Matemática - UNSAAC
  {
    id: 'q-unsaac-mat-001',
    text: '¿Cuánto es √144?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'turismo',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: '√144 = 12 porque 12² = 144',
    options: [
      { text: '12', isCorrect: true, orderIndex: 0 },
      { text: '14', isCorrect: false, orderIndex: 1 },
      { text: '11', isCorrect: false, orderIndex: 2 },
      { text: '72', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-002',
    text: 'Si 3x + 7 = 16, ¿cuál es el valor de x?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'administracion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: '3x = 16 - 7 = 9 → x = 9/3 = 3',
    options: [
      { text: '3', isCorrect: true, orderIndex: 0 },
      { text: '9', isCorrect: false, orderIndex: 1 },
      { text: '7', isCorrect: false, orderIndex: 2 },
      { text: '5', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-003',
    text: '¿Cuál es el área de un círculo de radio 7cm? (π ≈ 22/7)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-civil',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'A = πr² = (22/7)(49) = 154 cm²',
    options: [
      { text: '154 cm²', isCorrect: true, orderIndex: 0 },
      { text: '44 cm²', isCorrect: false, orderIndex: 1 },
      { text: '77 cm²', isCorrect: false, orderIndex: 2 },
      { text: '22 cm²', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-004',
    text: '¿Qué porcentaje es 25 de 200?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'administracion',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: '(25/200)×100% = 12.5%',
    options: [
      { text: '12.5%', isCorrect: true, orderIndex: 0 },
      { text: '25%', isCorrect: false, orderIndex: 1 },
      { text: '50%', isCorrect: false, orderIndex: 2 },
      { text: '8%', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-005',
    text: 'Hallar el perímetro de un rectángulo de 8cm × 5cm.',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'arquitectura',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'P = 2(L+A) = 2(8+5) = 26 cm',
    options: [
      { text: '26 cm', isCorrect: true, orderIndex: 0 },
      { text: '40 cm', isCorrect: false, orderIndex: 1 },
      { text: '13 cm', isCorrect: false, orderIndex: 2 },
      { text: '20 cm', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-006',
    text: '¿Cuánto es 15% de 80?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'economia-carrera',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: '15% de 80 = (15/100)×80 = 12',
    options: [
      { text: '12', isCorrect: true, orderIndex: 0 },
      { text: '15', isCorrect: false, orderIndex: 1 },
      { text: '8', isCorrect: false, orderIndex: 2 },
      { text: '20', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-007',
    text: '¿Cuál es el volumen de una esfera de radio 3cm? (V = 4/3 πr³)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-civil',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'V = 4/3 × π × 27 = 36π ≈ 113.1 cm³',
    options: [
      { text: '36π cm³', isCorrect: true, orderIndex: 0 },
      { text: '12π cm³', isCorrect: false, orderIndex: 1 },
      { text: '27π cm³', isCorrect: false, orderIndex: 2 },
      { text: '9π cm³', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-008',
    text: 'Resolver: 5x - 3 = 2x + 12',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-sistemas',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: '5x - 2x = 12 + 3 → 3x = 15 → x = 5',
    options: [
      { text: '5', isCorrect: true, orderIndex: 0 },
      { text: '3', isCorrect: false, orderIndex: 1 },
      { text: '15', isCorrect: false, orderIndex: 2 },
      { text: '9', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-009',
    text: '¿Cuántos lados tiene un hexágono?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'arquitectura',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'Hexágono = 6 lados (hex = 6)',
    options: [
      { text: '6', isCorrect: true, orderIndex: 0 },
      { text: '5', isCorrect: false, orderIndex: 1 },
      { text: '8', isCorrect: false, orderIndex: 2 },
      { text: '7', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-010',
    text: '¿Cuál es la suma de ángulos internos de un triángulo?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-civil',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'La suma de ángulos internos de todo triángulo es 180°.',
    options: [
      { text: '180°', isCorrect: true, orderIndex: 0 },
      { text: '360°', isCorrect: false, orderIndex: 1 },
      { text: '90°', isCorrect: false, orderIndex: 2 },
      { text: '270°', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-011',
    text: 'Si un tren recorre 240km en 3 horas, ¿cuál es su velocidad?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-industrial',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'v = d/t = 240km / 3h = 80 km/h',
    options: [
      { text: '80 km/h', isCorrect: true, orderIndex: 0 },
      { text: '60 km/h', isCorrect: false, orderIndex: 1 },
      { text: '720 km/h', isCorrect: false, orderIndex: 2 },
      { text: '40 km/h', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-mat-012',
    text: '¿Cuánto es 2⁴?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'matematica',
    careerId: 'ing-sistemas',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: '2⁴ = 2×2×2×2 = 16',
    options: [
      { text: '16', isCorrect: true, orderIndex: 0 },
      { text: '8', isCorrect: false, orderIndex: 1 },
      { text: '32', isCorrect: false, orderIndex: 2 },
      { text: '6', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Física - UNSAAC
  {
    id: 'q-unsaac-fis-001',
    text: '¿Cuál es la unidad de medida de la energía en el SI?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-civil',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'El Joule (J) es la unidad de energía en el Sistema Internacional.',
    options: [
      { text: 'Joule (J)', isCorrect: true, orderIndex: 0 },
      { text: 'Watt (W)', isCorrect: false, orderIndex: 1 },
      { text: 'Newton (N)', isCorrect: false, orderIndex: 2 },
      { text: 'Pascal (Pa)', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-fis-002',
    text: '¿Qué magnitudes son fundamentales en el SI?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-industrial',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Longitud, masa, tiempo, corriente eléctrica, temperatura, cantidad de sustancia e intensidad luminosa.',
    options: [
      { text: 'Longitud, masa, tiempo y otras 4', isCorrect: true, orderIndex: 0 },
      { text: 'Solo longitud y masa', isCorrect: false, orderIndex: 1 },
      { text: 'Solo masa y tiempo', isCorrect: false, orderIndex: 2 },
      { text: '7 magnitudes exactamente', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-fis-003',
    text: '¿Qué ley dice que la presión ejercida por un fluido es inversamente proporcional al volumen?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-quimica',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-II',
    explanation: 'Ley de Boyle: P₁V₁ = P₂V₂ a temperatura constante.',
    options: [
      { text: 'Ley de Boyle', isCorrect: true, orderIndex: 0 },
      { text: 'Ley de Charles', isCorrect: false, orderIndex: 1 },
      { text: 'Ley de Gay-Lussac', isCorrect: false, orderIndex: 2 },
      { text: 'Principio de Arquímedes', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-fis-004',
    text: '¿Qué es la potencia eléctrica?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'fisica',
    careerId: 'ing-electronica',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'P = VI, energía por unidad de tiempo (vatios, W).',
    options: [
      { text: 'Energía transferida por unidad de tiempo', isCorrect: true, orderIndex: 0 },
      { text: 'Carga eléctrica total', isCorrect: false, orderIndex: 1 },
      { text: 'Resistencia al flujo', isCorrect: false, orderIndex: 2 },
      { text: 'Diferencia de potencial', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Química - UNSAAC
  {
    id: 'q-unsaac-qui-001',
    text: '¿Qué es una solución buffer?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-quimica',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Una solución que resiste cambios de pH al añadir ácidos o bases.',
    options: [
      { text: 'Resiste cambios de pH', isCorrect: true, orderIndex: 0 },
      { text: 'Acelera reacciones químicas', isCorrect: false, orderIndex: 1 },
      { text: 'Tiene pH neutro', isCorrect: false, orderIndex: 2 },
      { text: 'Contiene solo agua', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-qui-002',
    text: '¿Qué tipo de enlace se forma entre Na y Cl?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'farmacia',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Metal (Na) + No metal (Cl) = Enlace iónico.',
    options: [
      { text: 'Iónico', isCorrect: true, orderIndex: 0 },
      { text: 'Covalente', isCorrect: false, orderIndex: 1 },
      { text: 'Metálico', isCorrect: false, orderIndex: 2 },
      { text: 'De hidrógeno', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-qui-003',
    text: '¿Cuál es la masa molar del CO₂? (C=12, O=16)',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'ing-quimica',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'M(CO₂) = 12 + 2(16) = 44 g/mol',
    options: [
      { text: '44 g/mol', isCorrect: true, orderIndex: 0 },
      { text: '28 g/mol', isCorrect: false, orderIndex: 1 },
      { text: '40 g/mol', isCorrect: false, orderIndex: 2 },
      { text: '60 g/mol', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-qui-004',
    text: '¿Qué significa pH = 7?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'quimica',
    careerId: 'farmacia',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'pH = 7 indica solución neutra (como el agua pura a 25°C).',
    options: [
      { text: 'Solución neutra', isCorrect: true, orderIndex: 0 },
      { text: 'Solución ácida', isCorrect: false, orderIndex: 1 },
      { text: 'Solución básica', isCorrect: false, orderIndex: 2 },
      { text: 'Solución muy ácida', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Comunicación - UNSAAC
  {
    id: 'q-unsaac-com-001',
    text: '¿Qué es un sustantivo?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'comunicacion',
    careerId: 'educacion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Palabra que designa personas, animales, cosas o ideas.',
    options: [
      { text: 'Palabra que nombra seres, lugares o ideas', isCorrect: true, orderIndex: 0 },
      { text: 'Palabra que indica acción', isCorrect: false, orderIndex: 1 },
      { text: 'Palabra que modifica al sustantivo', isCorrect: false, orderIndex: 2 },
      { text: 'Palabra que une términos', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-com-002',
    text: '¿Qué es el verbo?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'comunicacion',
    careerId: 'educacion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Palabra que expresa acción, estado o fenómenos naturales.',
    options: [
      { text: 'Palabra que expresa acción o estado', isCorrect: true, orderIndex: 0 },
      { text: 'Palabra que nombra objetos', isCorrect: false, orderIndex: 1 },
      { text: 'Palabra que califica sustantivos', isCorrect: false, orderIndex: 2 },
      { text: 'Palabra que une oraciones', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-com-003',
    text: '¿Qué tipo de texto es una noticia?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'comunicacion',
    careerId: 'comunicacion-social',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'La noticia es un texto informativo que comunica hechos actuales.',
    options: [
      { text: 'Informativo', isCorrect: true, orderIndex: 0 },
      { text: 'Narrativo', isCorrect: false, orderIndex: 1 },
      { text: 'Literario', isCorrect: false, orderIndex: 2 },
      { text: 'Publicitario', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Historia - UNSAAC
  {
    id: 'q-unsaac-hist-001',
    text: '¿Qué imperio se fundó en el Cusco en el siglo XIII?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'historia',
    careerId: 'turismo',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'El Tahuantinsuyo (Imperio Inca) se fundó en el siglo XIII.',
    options: [
      { text: 'Imperio Inca (Tahuantinsuyo)', isCorrect: true, orderIndex: 0 },
      { text: 'Imperio Wari', isCorrect: false, orderIndex: 1 },
      { text: 'Imperio Mochica', isCorrect: false, orderIndex: 2 },
      { text: 'Imperio Tiahuanaco', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-hist-002',
    text: '¿En qué siglo se descubrieron las Américas (1492)?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'historia',
    careerId: 'administracion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: '1492 = siglo XV (1401-1500).',
    options: [
      { text: 'Siglo XV', isCorrect: true, orderIndex: 0 },
      { text: 'Siglo XIV', isCorrect: false, orderIndex: 1 },
      { text: 'Siglo XVI', isCorrect: false, orderIndex: 2 },
      { text: 'Siglo XIII', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-hist-003',
    text: '¿Quién conquistó el Imperio Inca?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'historia',
    careerId: 'turismo',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Francisco Pizarro lideró la conquista del Tahuantinsuyo.',
    options: [
      { text: 'Francisco Pizarro', isCorrect: true, orderIndex: 0 },
      { text: 'Hernando de Soto', isCorrect: false, orderIndex: 1 },
      { text: 'Pedro de Alvarado', isCorrect: false, orderIndex: 2 },
      { text: 'Sebastián de Orellana', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-hist-004',
    text: '¿Qué fue la Rebelión de Túpac Amaru II (1780-1782)?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'historia',
    careerId: 'derecho',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Fue el principal movimiento independentista indigenous contra el dominio español.',
    options: [
      { text: 'Movimiento independentista indígena', isCorrect: true, orderIndex: 0 },
      { text: 'Guerra entre criollos', isCorrect: false, orderIndex: 1 },
      { text: 'Revuelta por esclavitud', isCorrect: false, orderIndex: 2 },
      { text: 'Rebelión por independencia de Brasil', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Geografía - UNSAAC
  {
    id: 'q-unsaac-geo-001',
    text: '¿Cuál es el río más largo del mundo?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'geografia',
    careerId: 'turismo',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'El río Amazonas (~6400km) es el más largo del mundo.',
    options: [
      { text: 'Amazonas', isCorrect: true, orderIndex: 0 },
      { text: 'Nilo', isCorrect: false, orderIndex: 1 },
      { text: 'Yangtsé', isCorrect: false, orderIndex: 2 },
      { text: 'Misisipi', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-geo-002',
    text: '¿Qué cordillera atraviesa el Perú de norte a sur?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'geografia',
    careerId: 'turismo',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'La Cordillera de los Andes recorre todo el Perú de norte a sur.',
    options: [
      { text: 'Cordillera de los Andes', isCorrect: true, orderIndex: 0 },
      { text: 'Cordillera Blanca', isCorrect: false, orderIndex: 1 },
      { text: 'Sierra Central', isCorrect: false, orderIndex: 2 },
      { text: 'Zona Interandina', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-geo-003',
    text: '¿Cuál es la capital del Cusco?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'geografia',
    careerId: 'turismo',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'Cusco es tanto ciudad como provincia, capital del Departamento del Cusco.',
    options: [
      { text: 'Cusco', isCorrect: true, orderIndex: 0 },
      { text: 'Arequipa', isCorrect: false, orderIndex: 1 },
      { text: 'Puno', isCorrect: false, orderIndex: 2 },
      { text: 'Juliaca', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Economía - UNSAAC
  {
    id: 'q-unsaac-eco-001',
    text: '¿Qué es el PBI (Producto Bruto Interno)?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'economia',
    careerId: 'administracion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Valor total de bienes y servicios producidos en un país en un año.',
    options: [
      { text: 'Valor total de bienes/servicios de un país', isCorrect: true, orderIndex: 0 },
      { text: 'Ingreso per cápita de la población', isCorrect: false, orderIndex: 1 },
      { text: 'Total de exportaciones', isCorrect: false, orderIndex: 2 },
      { text: 'Deuda externa de un país', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-eco-002',
    text: '¿Qué es la inflación?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'economia',
    careerId: 'administracion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Aumento generalizado y sostenido de precios en una economía.',
    options: [
      { text: 'Aumento generalizado de precios', isCorrect: true, orderIndex: 0 },
      { text: 'Caída de los precios', isCorrect: false, orderIndex: 1 },
      { text: 'Estabilidad de precios', isCorrect: false, orderIndex: 2 },
      { text: 'Aumento del desempleo', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-eco-003',
    text: '¿Qué es la ley de oferta y demanda?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'economia',
    careerId: 'economia-carrera',
    universityId: 'unsaac',
    examYear: 2022,
    examPeriod: '2022-I',
    explanation: 'El precio sube cuando la demanda supera a la oferta, y baja cuando ocurre lo contrario.',
    options: [
      { text: 'Precio sube si demanda > oferta', isCorrect: true, orderIndex: 0 },
      { text: 'El gobierno fija siempre los precios', isCorrect: false, orderIndex: 1 },
      { text: 'Precios siempre bajan', isCorrect: false, orderIndex: 2 },
      { text: 'Oferta y demanda nunca interactúan', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-eco-004',
    text: '¿Qué es el neoliberalismo económico?',
    difficulty: 'HARD' as DifficultyLevel,
    subjectId: 'economia',
    careerId: 'economia-carrera',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Modelo que promueve libre mercado, privatizaciones, desregulación y libre comercio.',
    options: [
      { text: 'Libre mercado, privatizaciones y desregulación', isCorrect: true, orderIndex: 0 },
      { text: 'Control total del Estado sobre la economía', isCorrect: false, orderIndex: 1 },
      { text: 'Economía planificada centralmente', isCorrect: false, orderIndex: 2 },
      { text: 'Nacionalización de empresas', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Filosofía - UNSAAC
  {
    id: 'q-unsaac-fil-001',
    text: '¿Quién escribió "El Príncipe"?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'filosofia',
    careerId: 'derecho',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Nicolás Maquiavelo escribió "El Príncipe" (1513).',
    options: [
      { text: 'Nicolás Maquiavelo', isCorrect: true, orderIndex: 0 },
      { text: 'Thomas Hobbes', isCorrect: false, orderIndex: 1 },
      { text: 'Jean-Jacques Rousseau', isCorrect: false, orderIndex: 2 },
      { text: 'Platón', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-fil-002',
    text: '¿Qué es el método dialéctico?',
    difficulty: 'MEDIUM' as DifficultyLevel,
    subjectId: 'filosofia',
    careerId: 'educacion',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'Método de conocimiento a través de tesis, antítesis y síntesis (Hegel).',
    options: [
      { text: 'Tesis + Antítesis = Síntesis', isCorrect: true, orderIndex: 0 },
      { text: 'Solo observación directa', isCorrect: false, orderIndex: 1 },
      { text: 'Experimentación de laboratorio', isCorrect: false, orderIndex: 2 },
      { text: 'Intuición pura del conocimiento', isCorrect: false, orderIndex: 3 },
    ],
  },

  // Biología - UNSAAC
  {
    id: 'q-unsaac-bio-001',
    text: '¿Qué organelo realiza la fotosíntesis?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'biologia',
    careerId: 'medicina',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-I',
    explanation: 'Los cloroplastos son los organelos responsáveis pela fotossíntesis.',
    options: [
      { text: 'Cloroplasto', isCorrect: true, orderIndex: 0 },
      { text: 'Mitocondria', isCorrect: false, orderIndex: 1 },
      { text: 'Ribosoma', isCorrect: false, orderIndex: 2 },
      { text: 'Núcleo', isCorrect: false, orderIndex: 3 },
    ],
  },
  {
    id: 'q-unsaac-bio-002',
    text: '¿Cuántos cromosomas tiene una célula humana?',
    difficulty: 'EASY' as DifficultyLevel,
    subjectId: 'biologia',
    careerId: 'medicina',
    universityId: 'unsaac',
    examYear: 2023,
    examPeriod: '2023-II',
    explanation: 'La célula humana diploide tiene 46 cromosomas (23 pares).',
    options: [
      { text: '46', isCorrect: true, orderIndex: 0 },
      { text: '23', isCorrect: false, orderIndex: 1 },
      { text: '48', isCorrect: false, orderIndex: 2 },
      { text: '44', isCorrect: false, orderIndex: 3 },
    ],
  },
];

async function main() {
  console.log('🌱 Seeding UNI & UNSAAC questions...');

  let created = 0;
  let skipped = 0;

  for (const q of questions) {
    const { options, ...questionData } = q;

    const existing = await prisma.question.findUnique({
      where: { id: questionData.id },
    });

    if (existing) {
      skipped++;
      console.log(`  ⏭️  Skip: "${questionData.text.substring(0, 40)}..." (${questionData.universityId})`);
      continue;
    }

    await prisma.question.create({
      data: {
        ...questionData,
        options: {
          create: options,
        },
      },
    });
    created++;
    console.log(`  ✅ ${questionData.universityId}: "${questionData.text.substring(0, 45)}..."`);
  }

  console.log(`\n✅ Done! Created ${created} new questions, skipped ${skipped} existing.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
