import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const unsaacQuestions = [
  { text: '¿Cuánto es √144?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: '√144 = 12', options: [{text:'12',isCorrect:true,orderIndex:0},{text:'14',isCorrect:false,orderIndex:1},{text:'11',isCorrect:false,orderIndex:2},{text:'72',isCorrect:false,orderIndex:3}] },
  { text: 'Si 3x + 7 = 16, ¿cuál es x?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: '3x=9 → x=3', options: [{text:'3',isCorrect:true,orderIndex:0},{text:'9',isCorrect:false,orderIndex:1},{text:'7',isCorrect:false,orderIndex:2},{text:'5',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuál es el área de un círculo de radio 7cm?', difficulty: 'MEDIUM' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'A=πr²=154cm²', options: [{text:'154 cm²',isCorrect:true,orderIndex:0},{text:'44 cm²',isCorrect:false,orderIndex:1},{text:'77 cm²',isCorrect:false,orderIndex:2},{text:'22 cm²',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué porcentaje es 25 de 200?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-II', explanation: '(25/200)×100=12.5%', options: [{text:'12.5%',isCorrect:true,orderIndex:0},{text:'25%',isCorrect:false,orderIndex:1},{text:'50%',isCorrect:false,orderIndex:2},{text:'8%',isCorrect:false,orderIndex:3}] },
  { text: 'Hallar el perímetro de un rectángulo de 8cm×5cm.', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'P=2(8+5)=26cm', options: [{text:'26 cm',isCorrect:true,orderIndex:0},{text:'40 cm',isCorrect:false,orderIndex:1},{text:'13 cm',isCorrect:false,orderIndex:2},{text:'20 cm',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuánto es 15% de 80?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: '(15/100)×80=12', options: [{text:'12',isCorrect:true,orderIndex:0},{text:'15',isCorrect:false,orderIndex:1},{text:'8',isCorrect:false,orderIndex:2},{text:'20',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuántos lados tiene un hexágono?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-I', explanation: 'Hex=6', options: [{text:'6',isCorrect:true,orderIndex:0},{text:'5',isCorrect:false,orderIndex:1},{text:'8',isCorrect:false,orderIndex:2},{text:'7',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuál es la suma de ángulos internos de un triángulo?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Siempre 180°', options: [{text:'180°',isCorrect:true,orderIndex:0},{text:'360°',isCorrect:false,orderIndex:1},{text:'90°',isCorrect:false,orderIndex:2},{text:'270°',isCorrect:false,orderIndex:3}] },
  { text: 'Si un tren recorre 240km en 3h, ¿cuál es su velocidad?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'v=240/3=80km/h', options: [{text:'80 km/h',isCorrect:true,orderIndex:0},{text:'60 km/h',isCorrect:false,orderIndex:1},{text:'720 km/h',isCorrect:false,orderIndex:2},{text:'40 km/h',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuánto es 2⁴?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-I', explanation: '2×2×2×2=16', options: [{text:'16',isCorrect:true,orderIndex:0},{text:'8',isCorrect:false,orderIndex:1},{text:'32',isCorrect:false,orderIndex:2},{text:'6',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuánto es 5² + 3³?', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: '25+27=52', options: [{text:'52',isCorrect:true,orderIndex:0},{text:'28',isCorrect:false,orderIndex:1},{text:'15',isCorrect:false,orderIndex:2},{text:'125',isCorrect:false,orderIndex:3}] },
  { text: 'Resolver: 2x + 4 = 10', difficulty: 'EASY' as const, subjectId: 'matematica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: '2x=6 → x=3', options: [{text:'3',isCorrect:true,orderIndex:0},{text:'2',isCorrect:false,orderIndex:1},{text:'6',isCorrect:false,orderIndex:2},{text:'5',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuál es la unidad de medida de la energía en el SI?', difficulty: 'EASY' as const, subjectId: 'fisica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Joule (J)', options: [{text:'Joule (J)',isCorrect:true,orderIndex:0},{text:'Watt (W)',isCorrect:false,orderIndex:1},{text:'Newton (N)',isCorrect:false,orderIndex:2},{text:'Pascal (Pa)',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué tipo de energía tiene un auto en movimiento?', difficulty: 'EASY' as const, subjectId: 'fisica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'Ec=½mv²', options: [{text:'Cinética',isCorrect:true,orderIndex:0},{text:'Potencial',isCorrect:false,orderIndex:1},{text:'Térmica',isCorrect:false,orderIndex:2},{text:'Química',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué ley dice P1V1=P2V2?', difficulty: 'MEDIUM' as const, subjectId: 'fisica', careerId: 'administracion', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-II', explanation: 'Ley de Boyle', options: [{text:'Ley de Boyle',isCorrect:true,orderIndex:0},{text:'Ley de Charles',isCorrect:false,orderIndex:1},{text:'Ley de Gay-Lussac',isCorrect:false,orderIndex:2},{text:'Principio de Arquímedes',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es la potencia eléctrica?', difficulty: 'EASY' as const, subjectId: 'fisica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'P=VI, energía/tiempo', options: [{text:'Energía por unidad de tiempo',isCorrect:true,orderIndex:0},{text:'Carga eléctrica total',isCorrect:false,orderIndex:1},{text:'Resistencia al flujo',isCorrect:false,orderIndex:2},{text:'Diferencia de potencial',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué tipo de enlace se forma entre Na y Cl?', difficulty: 'EASY' as const, subjectId: 'quimica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Metal+No metal=iónico', options: [{text:'Iónico',isCorrect:true,orderIndex:0},{text:'Covalente',isCorrect:false,orderIndex:1},{text:'Metálico',isCorrect:false,orderIndex:2},{text:'De hidrógeno',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuál es la masa molar del CO2? (C=12, O=16)', difficulty: 'MEDIUM' as const, subjectId: 'quimica', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: '12+32=44g/mol', options: [{text:'44 g/mol',isCorrect:true,orderIndex:0},{text:'28 g/mol',isCorrect:false,orderIndex:1},{text:'40 g/mol',isCorrect:false,orderIndex:2},{text:'60 g/mol',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué significa pH = 7?', difficulty: 'EASY' as const, subjectId: 'quimica', careerId: 'administracion', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-I', explanation: 'Neutro', options: [{text:'Solución neutra',isCorrect:true,orderIndex:0},{text:'Solución ácida',isCorrect:false,orderIndex:1},{text:'Solución básica',isCorrect:false,orderIndex:2},{text:'Muy ácida',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es un sustantivo?', difficulty: 'EASY' as const, subjectId: 'comunicacion', careerId: 'educacion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Palabra que nombra', options: [{text:'Palabra que nombra seres/cosas',isCorrect:true,orderIndex:0},{text:'Palabra que indica acción',isCorrect:false,orderIndex:1},{text:'Palabra que modifica',isCorrect:false,orderIndex:2},{text:'Palabra que une',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es el verbo?', difficulty: 'EASY' as const, subjectId: 'comunicacion', careerId: 'educacion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'Expresa acción/estado', options: [{text:'Expresa acción o estado',isCorrect:true,orderIndex:0},{text:'Nombra objetos',isCorrect:false,orderIndex:1},{text:'Califica sustantivos',isCorrect:false,orderIndex:2},{text:'Une oraciones',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué tipo de texto es una noticia?', difficulty: 'EASY' as const, subjectId: 'comunicacion', careerId: 'comunicacion-social', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-I', explanation: 'Informa hechos actuales', options: [{text:'Informativo',isCorrect:true,orderIndex:0},{text:'Narrativo',isCorrect:false,orderIndex:1},{text:'Literario',isCorrect:false,orderIndex:2},{text:'Publicitario',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué imperio se fundó en el Cusco?', difficulty: 'EASY' as const, subjectId: 'historia', careerId: 'turismo', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Tahuantinsuyo (Inca)', options: [{text:'Imperio Inca',isCorrect:true,orderIndex:0},{text:'Imperio Wari',isCorrect:false,orderIndex:1},{text:'Imperio Mochica',isCorrect:false,orderIndex:2},{text:'Imperio Tiahuanaco',isCorrect:false,orderIndex:3}] },
  { text: '¿En qué siglo se descubrieron las Américas?', difficulty: 'EASY' as const, subjectId: 'historia', careerId: 'turismo', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: '1492 = siglo XV', options: [{text:'Siglo XV',isCorrect:true,orderIndex:0},{text:'Siglo XIV',isCorrect:false,orderIndex:1},{text:'Siglo XVI',isCorrect:false,orderIndex:2},{text:'Siglo XIII',isCorrect:false,orderIndex:3}] },
  { text: '¿Quién conquistó el Imperio Inca?', difficulty: 'EASY' as const, subjectId: 'historia', careerId: 'turismo', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Francisco Pizarro', options: [{text:'Francisco Pizarro',isCorrect:true,orderIndex:0},{text:'Hernando de Soto',isCorrect:false,orderIndex:1},{text:'Pedro de Alvarado',isCorrect:false,orderIndex:2},{text:'Sebastián de Orellana',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué fue la Rebelión de Túpac Amaru II?', difficulty: 'MEDIUM' as const, subjectId: 'historia', careerId: 'derecho', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'Movimiento independentista indígena', options: [{text:'Movimiento independentista indígena',isCorrect:true,orderIndex:0},{text:'Guerra entre criollos',isCorrect:false,orderIndex:1},{text:'Revuelta por esclavitud',isCorrect:false,orderIndex:2},{text:'Rebelión por independencia de Brasil',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuál es el río más largo del mundo?', difficulty: 'EASY' as const, subjectId: 'geografia', careerId: 'turismo', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Amazonas (~6400km)', options: [{text:'Amazonas',isCorrect:true,orderIndex:0},{text:'Nilo',isCorrect:false,orderIndex:1},{text:'Yangtsé',isCorrect:false,orderIndex:2},{text:'Misisipi',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué cordillera atraviesa el Perú?', difficulty: 'EASY' as const, subjectId: 'geografia', careerId: 'turismo', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'Cordillera de los Andes', options: [{text:'Cordillera de los Andes',isCorrect:true,orderIndex:0},{text:'Cordillera Blanca',isCorrect:false,orderIndex:1},{text:'Sierra Central',isCorrect:false,orderIndex:2},{text:'Zona Interandina',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es el PBI?', difficulty: 'MEDIUM' as const, subjectId: 'economia', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Valor total bienes/servicios de un país', options: [{text:'Valor total de bienes/servicios',isCorrect:true,orderIndex:0},{text:'Ingreso per cápita',isCorrect:false,orderIndex:1},{text:'Total de exportaciones',isCorrect:false,orderIndex:2},{text:'Deuda externa',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es la inflación?', difficulty: 'EASY' as const, subjectId: 'economia', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'Aumento generalizado de precios', options: [{text:'Aumento generalizado de precios',isCorrect:true,orderIndex:0},{text:'Caída de precios',isCorrect:false,orderIndex:1},{text:'Estabilidad de precios',isCorrect:false,orderIndex:2},{text:'Aumento del desempleo',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es la ley de oferta y demanda?', difficulty: 'MEDIUM' as const, subjectId: 'economia', careerId: 'economia-carrera', universityId: 'unsaac', examYear: 2022, examPeriod: '2022-I', explanation: 'Precio sube si demanda>oferta', options: [{text:'Precio sube si demanda > oferta',isCorrect:true,orderIndex:0},{text:'El gobierno fija siempre los precios',isCorrect:false,orderIndex:1},{text:'Precios siempre bajan',isCorrect:false,orderIndex:2},{text:'Oferta y demanda nunca interactúan',isCorrect:false,orderIndex:3}] },
  { text: '¿Quién escribió El Príncipe?', difficulty: 'EASY' as const, subjectId: 'filosofia', careerId: 'derecho', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Nicolás Maquiavelo (1513)', options: [{text:'Nicolás Maquiavelo',isCorrect:true,orderIndex:0},{text:'Thomas Hobbes',isCorrect:false,orderIndex:1},{text:'Jean-Jacques Rousseau',isCorrect:false,orderIndex:2},{text:'Platón',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué es el método dialéctico?', difficulty: 'MEDIUM' as const, subjectId: 'filosofia', careerId: 'educacion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: 'Tesis+Antítesis=Síntesis (Hegel)', options: [{text:'Tesis + Antítesis = Síntesis',isCorrect:true,orderIndex:0},{text:'Solo observación directa',isCorrect:false,orderIndex:1},{text:'Experimentación de laboratorio',isCorrect:false,orderIndex:2},{text:'Intuición pura del conocimiento',isCorrect:false,orderIndex:3}] },
  { text: '¿Qué organelo realiza la fotosíntesis?', difficulty: 'EASY' as const, subjectId: 'biologia', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-I', explanation: 'Cloroplasto', options: [{text:'Cloroplasto',isCorrect:true,orderIndex:0},{text:'Mitocondria',isCorrect:false,orderIndex:1},{text:'Ribosoma',isCorrect:false,orderIndex:2},{text:'Núcleo',isCorrect:false,orderIndex:3}] },
  { text: '¿Cuántos cromosomas tiene una célula humana?', difficulty: 'EASY' as const, subjectId: 'biologia', careerId: 'administracion', universityId: 'unsaac', examYear: 2023, examPeriod: '2023-II', explanation: '46 cromosomas (23 pares)', options: [{text:'46',isCorrect:true,orderIndex:0},{text:'23',isCorrect:false,orderIndex:1},{text:'48',isCorrect:false,orderIndex:2},{text:'44',isCorrect:false,orderIndex:3}] },
];

async function main() {
  let count = 0;
  for (const q of unsaacQuestions) {
    const { options, ...qData } = q;
    const id = 'unsaac-' + Math.random().toString(36).substr(2, 9);
    try {
      await prisma.question.create({
        data: { id, ...qData, isActive: true, options: { create: options } }
      });
      count++;
    } catch(e) { console.log('Error:', e.message); }
  }
  console.log('UNSAAC: added ' + count + ' questions');
}
main().then(() => prisma.$disconnect());
