import 'dotenv/config';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const FICTIONAL_QUESTIONS: Array<{
  universityId: string;
  subjectId: string;
  careerId?: string;
  questions: Array<{
    text: string;
    difficulty: 'EASY' | 'MEDIUM' | 'HARD';
    explanation: string;
    options: Array<{ text: string; isCorrect: boolean }>;
  }>;
}> = [
  // UNI - Historia
  { universityId: 'uni', subjectId: 'historia', questions: [
    { text: '¿En qué año se fundó la Universidad Nacional de Ingeniería?', difficulty: 'MEDIUM', explanation: 'La UNI fue fundada el 19 de diciembre de 1876.', options: [{ text: '1876', isCorrect: true }, { text: '1890', isCorrect: false }, { text: '1850', isCorrect: false }, { text: '1900', isCorrect: false }, { text: '1910', isCorrect: false }] },
    { text: '¿Quién fue el primer presidente del Perú después de la independencia?', difficulty: 'EASY', explanation: 'José de San Martín fue proclamado Protector del Perú.', options: [{ text: 'José de San Martín', isCorrect: true }, { text: 'Simón Bolívar', isCorrect: false }, { text: 'Antonio José de Sucre', isCorrect: false }, { text: 'Andrés de Santa Cruz', isCorrect: false }, { text: 'Ramón Castilla', isCorrect: false }] },
    { text: '¿Cuál fue la causa principal de la Guerra del Pacífico?', difficulty: 'HARD', explanation: 'La Guerra del Pacífico (1879-1884) se originó por la disputa sobre las minas de salitre en Antofagasta.', options: [{ text: 'Disputa por las minas de salitre en Antofagasta', isCorrect: true }, { text: 'Conflicto por límites amazónicos', isCorrect: false }, { text: 'Competencia comercial', isCorrect: false }, { text: 'Agresión chilena a la industria textil', isCorrect: false }, { text: 'Nacionalización de empresas', isCorrect: false }] },
    { text: '¿Qué imperio anexó el Tahuantinsuyo al Imperio español?', difficulty: 'EASY', explanation: 'El Tawantinsuyo fue anexado con la captura de Atahualpa en 1533.', options: [{ text: 'Imperio español', isCorrect: true }, { text: 'Imperio portugués', isCorrect: false }, { text: 'Imperio británico', isCorrect: false }, { text: 'Imperio holandés', isCorrect: false }, { text: 'Imperio francés', isCorrect: false }] },
    { text: '¿En qué siglo ocurrió el movimiento de independencia del Perú?', difficulty: 'EASY', explanation: 'El movimiento de independencia se desarrolló en el siglo XIX.', options: [{ text: 'Siglo XIX', isCorrect: true }, { text: 'Siglo XVIII', isCorrect: false }, { text: 'Siglo XX', isCorrect: false }, { text: 'Siglo XVII', isCorrect: false }, { text: 'Siglo XVIII', isCorrect: false }] },
    { text: '¿Qué tratado puso fin a la Guerra del Pacífico?', difficulty: 'HARD', explanation: 'El Tratado de Ancón (1883) puso fin a la Guerra del Pacífico.', options: [{ text: 'Tratado de Ancón', isCorrect: true }, { text: 'Tratado de Lima', isCorrect: false }, { text: 'Tratado de San Martín', isCorrect: false }, { text: 'Protocolo de paz', isCorrect: false }, { text: 'Armisticio de Arica', isCorrect: false }] },
    { text: '¿Quién lideró la resistencia indígena contra los españoles en el siglo XVIII?', difficulty: 'MEDIUM', explanation: 'Túpac Amaru II fue el líder de la gran rebelión indígena de 1780-1782.', options: [{ text: 'Túpac Amaru II', isCorrect: true }, { text: 'Manco Inca', isCorrect: false }, { text: 'Titu Cusi', isCorrect: false }, { text: 'Atahualpa', isCorrect: false }, { text: 'Quispisanka', isCorrect: false }] },
    { text: '¿Qué civilización descubrió Caral?', difficulty: 'MEDIUM', explanation: 'Caral fue descubierta en 1994 por Ruth Shady, siendo la civilización más antigua de América.', options: [{ text: 'Civilización Caral (5,000 años)', isCorrect: true }, { text: 'Cultura Moche', isCorrect: false }, { text: 'Cultura Nazca', isCorrect: false }, { text: 'Imperio Wari', isCorrect: false }, { text: 'Cultura Paracas', isCorrect: false }] },
    { text: '¿Qué país colonizó principalmente la región andina del Perú?', difficulty: 'EASY', explanation: 'España fue el país que colonizó el territorio del actual Perú.', options: [{ text: 'España', isCorrect: true }, { text: 'Portugal', isCorrect: false }, { text: 'Inglaterra', isCorrect: false }, { text: 'Francia', isCorrect: false }, { text: 'Holanda', isCorrect: false }] },
    { text: '¿Qué ley marcó la educación republicana en el Perú?', difficulty: 'HARD', explanation: 'La Ley de Educación Común de 1903 estableció las bases de la educación pública.', options: [{ text: 'Ley de Educación Común de 1903', isCorrect: true }, { text: 'Constitución de 1823', isCorrect: false }, { text: 'Ley de 1850', isCorrect: false }, { text: 'Reforma de 1972', isCorrect: false }, { text: 'Ninguna', isCorrect: false }] },
  ]},
  // UNI - Geografía
  { universityId: 'uni', subjectId: 'geografia', questions: [
    { text: '¿Cuál es la capital del Perú?', difficulty: 'EASY', explanation: 'Lima es la capital del Perú.', options: [{ text: 'Lima', isCorrect: true }, { text: 'Arequipa', isCorrect: false }, { text: 'Cusco', isCorrect: false }, { text: 'Trujillo', isCorrect: false }, { text: 'Iquitos', isCorrect: false }] },
    { text: '¿Qué cordillera atraviesa el Perú?', difficulty: 'MEDIUM', explanation: 'La Cordillera de los Andes atraviesa todo el Perú de norte a sur.', options: [{ text: 'Cordillera de los Andes', isCorrect: true }, { text: 'Cordillera Oriental', isCorrect: false }, { text: 'Sierra Madre', isCorrect: false }, { text: 'Macizo Boliviano', isCorrect: false }, { text: 'Alpes Peruanos', isCorrect: false }] },
    { text: '¿Qué ecosistema se encuentra en la costa norte del Perú?', difficulty: 'MEDIUM', explanation: 'El desierto costero con influencia de la corriente de Humboldt.', options: [{ text: 'Desierto costero tropical', isCorrect: true }, { text: 'Selva tropical', isCorrect: false }, { text: 'Bosque nublado', isCorrect: false }, { text: 'Puna andina', isCorrect: false }, { text: 'Sabana', isCorrect: false }] },
    { text: '¿Qué río es el más largo del Perú?', difficulty: 'HARD', explanation: 'El río Ucayali tiene aproximadamente 2,700 km.', options: [{ text: 'Río Ucayali', isCorrect: true }, { text: 'Río Amazonas', isCorrect: false }, { text: 'Río Marañón', isCorrect: false }, { text: 'Río Mantaro', isCorrect: false }, { text: 'Río Putumayo', isCorrect: false }] },
    { text: '¿Qué región natural del Perú tiene la mayor biodiversidad?', difficulty: 'MEDIUM', explanation: 'La Amazonía o selva baja tiene la mayor biodiversidad.', options: [{ text: 'Selva baja (Amazonía)', isCorrect: true }, { text: 'Costa', isCorrect: false }, { text: 'Sierra', isCorrect: false }, { text: 'Sierra alta', isCorrect: false }, { text: 'Costa desértica', isCorrect: false }] },
    { text: '¿Cuál es el punto más alto del Perú?', difficulty: 'HARD', explanation: 'El Huascarán, con 6,768 m, es la montaña más alta.', options: [{ text: 'Huascarán', isCorrect: true }, { text: 'Yerupajá', isCorrect: false }, { text: 'Coropuna', isCorrect: false }, { text: 'Ausangate', isCorrect: false }, { text: 'Salkantay', isCorrect: false }] },
    { text: '¿Qué corriente marina afecta la costa peruana?', difficulty: 'MEDIUM', explanation: 'La corriente de Humboldt trae aguas frías desde la Antártida.', options: [{ text: 'Corriente de Humboldt', isCorrect: true }, { text: 'Corriente del Niño', isCorrect: false }, { text: 'Corriente Ecuatorial del Sur', isCorrect: false }, { text: 'Corriente de Brasil', isCorrect: false }, { text: 'Corriente de Cromwell', isCorrect: false }] },
    { text: '¿Cuántos departamentos tiene el Perú?', difficulty: 'EASY', explanation: 'El Perú tiene 24 departamentos.', options: [{ text: '24', isCorrect: true }, { text: '25', isCorrect: false }, { text: '23', isCorrect: false }, { text: '26', isCorrect: false }, { text: '22', isCorrect: false }] },
    { text: '¿Qué lago es el más grande del Perú?', difficulty: 'MEDIUM', explanation: 'El lago Titicaca, compartido con Bolivia, es el lago navegable más alto del mundo.', options: [{ text: 'Lago Titicaca', isCorrect: true }, { text: 'Lago Junín', isCorrect: false }, { text: 'Lago Poopó', isCorrect: false }, { text: 'Lago Rimac', isCorrect: false }, { text: 'Lago Amazonás', isCorrect: false }] },
    { text: '¿Qué tipo de clima predomina en Lima?', difficulty: 'EASY', explanation: 'Lima tiene un clima desértico cálido con alta humedad.', options: [{ text: 'Desértico cálido con alta humedad', isCorrect: true }, { text: 'Tropical lluvioso', isCorrect: false }, { text: 'Semiárido frío', isCorrect: false }, { text: 'Oceanico costero', isCorrect: false }, { text: 'Montano frío', isCorrect: false }] },
  ]},
  // UNI - Economía
  { universityId: 'uni', subjectId: 'economia', questions: [
    { text: '¿Qué es el PBI?', difficulty: 'EASY', explanation: 'El Producto Bruto Interno mide el valor de bienes y servicios producidos en un país.', options: [{ text: 'Producto Bruto Interno', isCorrect: true }, { text: 'Producto Bruto Nacional', isCorrect: false }, { text: 'Producto Neto Interno', isCorrect: false }, { text: 'Presupuesto Básico Integral', isCorrect: false }, { text: 'Plan Básico Industrial', isCorrect: false }] },
    { text: '¿Qué es la inflación?', difficulty: 'EASY', explanation: 'La inflación es el aumento generalizado y sostenido de los precios.', options: [{ text: 'Aumento generalizado de precios', isCorrect: true }, { text: 'Disminución de precios', isCorrect: false }, { text: 'Estabilidad de precios', isCorrect: false }, { text: 'Aumento del empleo', isCorrect: false }, { text: 'Reducción de la deuda', isCorrect: false }] },
    { text: '¿Qué producto es el principal exportador del Perú?', difficulty: 'MEDIUM', explanation: 'El cobre es el principal producto de exportación del Perú.', options: [{ text: 'Cobre', isCorrect: true }, { text: 'Oro', isCorrect: false }, { text: 'Plata', isCorrect: false }, { text: 'Zinc', isCorrect: false }, { text: 'Petroleo', isCorrect: false }] },
    { text: '¿Qué es el tipo de cambio?', difficulty: 'EASY', explanation: 'El tipo de cambio es el precio de una moneda respecto a otra.', options: [{ text: 'Precio de una moneda en otra', isCorrect: true }, { text: 'Tasa de interés bancaria', isCorrect: false }, { text: 'Inflación anual', isCorrect: false }, { text: 'Deuda externa', isCorrect: false }, { text: 'PBI per cápita', isCorrect: false }] },
    { text: '¿Qué organismo internacional presta ayuda al Perú?', difficulty: 'EASY', explanation: 'El Fondo Monetario Internacional (FMI) presta ayuda financiera.', options: [{ text: 'Fondo Monetario Internacional', isCorrect: true }, { text: 'UNESCO', isCorrect: false }, { text: 'OMS', isCorrect: false }, { text: 'OEA', isCorrect: false }, { text: 'UNICEF', isCorrect: false }] },
    { text: '¿Qué es la minería para la economía peruana?', difficulty: 'MEDIUM', explanation: 'La minería es el sector más importante de las exportaciones.', options: [{ text: 'Principal fuente de exportaciones', isCorrect: true }, { text: 'Menor fuente de ingresos', isCorrect: false }, { text: 'Sector en decrecimiento', isCorrect: false }, { text: 'No tiene relevancia', isCorrect: false }, { text: 'Solo para empleo rural', isCorrect: false }] },
    { text: '¿Qué significa BCR?', difficulty: 'EASY', explanation: 'BCR significa Banco Central de Reserva del Perú.', options: [{ text: 'Banco Central de Reserva', isCorrect: true }, { text: 'Banco Comercial del Perú', isCorrect: false }, { text: 'Bolsa de Valores de Lima', isCorrect: false }, { text: 'Banco de Crédito', isCorrect: false }, { text: 'Contraloría General', isCorrect: false }] },
    { text: '¿Qué es el mercado cambiario?', difficulty: 'MEDIUM', explanation: 'El mercado cambiario (forex) es donde se intercambian monedas.', options: [{ text: 'Mercado de intercambio de monedas', isCorrect: true }, { text: 'Mercado de acciones', isCorrect: false }, { text: 'Mercado de bonos', isCorrect: false }, { text: 'Mercado de deudas', isCorrect: false }, { text: 'Mercado de Commodities', isCorrect: false }] },
    { text: '¿Qué es una recesión económica?', difficulty: 'MEDIUM', explanation: 'Una recesión es una caída del PBI durante dos o más trimestres.', options: [{ text: 'Caída del PBI por 2+ trimestres', isCorrect: true }, { text: 'Crecimiento lento', isCorrect: false }, { text: 'Aumento del desempleo', isCorrect: false }, { text: 'Inflación moderada', isCorrect: false }, { text: 'Expansión económica', isCorrect: false }] },
    { text: '¿Qué es la deuda externa?', difficulty: 'EASY', explanation: 'La deuda externa es el dinero que un país debe a organismos extranjeros.', options: [{ text: 'Dinero que un país debe al exterior', isCorrect: true }, { text: 'Dinero dentro del país', isCorrect: false }, { text: 'Inversiones extranjeras', isCorrect: false }, { text: 'Depósitos bancarios', isCorrect: false }, { text: 'Impuestos collected', isCorrect: false }] },
  ]},
  // UNI - Filosofía
  { universityId: 'uni', subjectId: 'filosofia', questions: [
    { text: '¿Quién escribió "El contrato social"?', difficulty: 'EASY', explanation: 'Jean-Jacques Rousseau escribió "El contrato social" (1762).', options: [{ text: 'Jean-Jacques Rousseau', isCorrect: true }, { text: 'John Locke', isCorrect: false }, { text: 'Montesquieu', isCorrect: false }, { text: 'Hobbes', isCorrect: false }, { text: 'Voltaire', isCorrect: false }] },
    { text: '¿Qué es la ética?', difficulty: 'EASY', explanation: 'La ética estudia la moral y los valores humanos.', options: [{ text: 'Estudio de la moral y los valores', isCorrect: true }, { text: 'Estudio de la lógica', isCorrect: false }, { text: 'Estudio de la naturaleza', isCorrect: false }, { text: 'Estudio del lenguaje', isCorrect: false }, { text: 'Estudio de la historia', isCorrect: false }] },
    { text: '¿Qué es el materialismo histórico?', difficulty: 'HARD', explanation: 'El materialismo histórico, de Marx, sostiene que las condiciones materiales determinan la estructura social.', options: [{ text: 'Teoría de Marx sobre determinación material', isCorrect: true }, { text: 'Filosofía idealista alemana', isCorrect: false }, { text: 'Teoría de la evolución social', isCorrect: false }, { text: 'Doctrina de la ilustración', isCorrect: false }, { text: 'Pensamiento neoliberal', isCorrect: false }] },
    { text: '¿Qué propone el existencialismo?', difficulty: 'MEDIUM', explanation: 'El existencialismo propone que la existencia precede a la esencia.', options: [{ text: 'La existencia precede a la esencia', isCorrect: true }, { text: 'El ser determina la conciencia', isCorrect: false }, { text: 'Dios existe necesariamente', isCorrect: false }, { text: 'El conocimiento es innato', isCorrect: false }, { text: 'La realidad es una ilusión', isCorrect: false }] },
    { text: '¿Quién es el autor de "Ser y tiempo"?', difficulty: 'HARD', explanation: 'Martin Heidegger escribió "Ser y tiempo" (1927).', options: [{ text: 'Martin Heidegger', isCorrect: true }, { text: 'Jean-Paul Sartre', isCorrect: false }, { text: 'Karl Jaspers', isCorrect: false }, { text: 'Maurice Merleau-Ponty', isCorrect: false }, { text: 'Albert Camus', isCorrect: false }] },
    { text: '¿Qué es la epistemología?', difficulty: 'MEDIUM', explanation: 'La epistemología estudia el conocimiento.', options: [{ text: 'Teoría del conocimiento', isCorrect: true }, { text: 'Teoría de la moral', isCorrect: false }, { text: 'Teoría del lenguaje', isCorrect: false }, { text: 'Teoría de la percepción', isCorrect: false }, { text: 'Teoría de la mente', isCorrect: false }] },
    { text: '¿Qué es la lógica formal?', difficulty: 'MEDIUM', explanation: 'La lógica formal estudia los principios del razonamiento válido.', options: [{ text: 'Estudio del razonamiento válido', isCorrect: true }, { text: 'Estudio de emociones', isCorrect: false }, { text: 'Estudio del lenguaje', isCorrect: false }, { text: 'Estudio de la historia', isCorrect: false }, { text: 'Estudio del ser', isCorrect: false }] },
    { text: '¿Qué filósofo dijo "Pienso, luego existo"?', difficulty: 'EASY', explanation: 'René Descartes formuló "Cogito, ergo sum".', options: [{ text: 'René Descartes', isCorrect: true }, { text: 'Baruch Spinoza', isCorrect: false }, { text: 'Gottfried Leibniz', isCorrect: false }, { text: 'Immanuel Kant', isCorrect: false }, { text: 'Georg Hegel', isCorrect: false }] },
    { text: '¿Qué es el a priori en Kant?', difficulty: 'HARD', explanation: 'Kant llamó "a priori" al conocimiento independiente de la experiencia.', options: [{ text: 'Conocimiento independiente de la experiencia', isCorrect: true }, { text: 'Conocimiento basado en experiencia', isCorrect: false }, { text: 'Conocimiento religioso', isCorrect: false }, { text: 'Conocimiento científico', isCorrect: false }, { text: 'Conocimiento emocional', isCorrect: false }] },
    { text: '¿Qué es el utilitarismo?', difficulty: 'MEDIUM', explanation: 'El utilitarismo busca el mayor bien para el mayor número.', options: [{ text: 'Mayor bien para el mayor número', isCorrect: true }, { text: 'Derechos individuales absolutos', isCorrect: false }, { text: 'Bien común basado en tradición', isCorrect: false }, { text: 'Libertad económica total', isCorrect: false }, { text: 'Justicia social', isCorrect: false }] },
  ]},
  // UNI - Biología
  { universityId: 'uni', subjectId: 'biologia', questions: [
    { text: '¿Qué organelo es la "central energética" de la célula?', difficulty: 'EASY', explanation: 'Las mitocondrias producen ATP, la energía celular.', options: [{ text: 'Mitocondria', isCorrect: true }, { text: 'Núcleo', isCorrect: false }, { text: 'Ribosoma', isCorrect: false }, { text: 'Lisosoma', isCorrect: false }, { text: 'Aparato de Golgi', isCorrect: false }] },
    { text: '¿Qué es la fotosíntesis?', difficulty: 'EASY', explanation: 'La fotosíntesis convierte CO2 y luz en glucosa.', options: [{ text: 'Conversión de luz en glucosa', isCorrect: true }, { text: 'Respiración celular', isCorrect: false }, { text: 'División celular', isCorrect: false }, { text: 'Fermentación', isCorrect: false }, { text: 'Digestión vegetal', isCorrect: false }] },
    { text: '¿Cuántos cromosomas tiene una célula humana?', difficulty: 'MEDIUM', explanation: 'La célula humana tiene 46 cromosomas (23 pares).', options: [{ text: '46', isCorrect: true }, { text: '44', isCorrect: false }, { text: '48', isCorrect: false }, { text: '42', isCorrect: false }, { text: '23', isCorrect: false }] },
    { text: '¿Qué es el ADN?', difficulty: 'EASY', explanation: 'El ADN porta la información genética.', options: [{ text: 'Ácido desoxirribonucleico', isCorrect: true }, { text: 'Ácido ribonucleico', isCorrect: false }, { text: 'Proteína estructural', isCorrect: false }, { text: 'Lípido genético', isCorrect: false }, { text: 'Carbohidrato informativo', isCorrect: false }] },
    { text: '¿Qué tipo de célula tienen las plantas?', difficulty: 'EASY', explanation: 'Las plantas tienen células eucariotas con pared celular.', options: [{ text: 'Eucariota con pared celular', isCorrect: true }, { text: 'Procariota', isCorrect: false }, { text: 'Animal', isCorrect: false }, { text: 'Hongos', isCorrect: false }, { text: 'Sin núcleo', isCorrect: false }] },
    { text: '¿Qué es la mitosis?', difficulty: 'MEDIUM', explanation: 'La mitosis produce células hija genéticamente idénticas.', options: [{ text: 'División celular idéntica', isCorrect: true }, { text: 'Unión de células', isCorrect: false }, { text: 'Muerte celular', isCorrect: false }, { text: 'Transformación celular', isCorrect: false }, { text: 'Duplicación del ADN', isCorrect: false }] },
    { text: '¿Qué vitaminas produce la piel con la exposición al sol?', difficulty: 'MEDIUM', explanation: 'La exposición al sol permite producir vitamina D.', options: [{ text: 'Vitamina D', isCorrect: true }, { text: 'Vitamina A', isCorrect: false }, { text: 'Vitamina C', isCorrect: false }, { text: 'Vitamina B12', isCorrect: false }, { text: 'Vitamina E', isCorrect: false }] },
    { text: '¿Qué órgano filtra la sangre?', difficulty: 'EASY', explanation: 'Los riñones filtran la sangre y producen orina.', options: [{ text: 'Riñón', isCorrect: true }, { text: 'Hígado', isCorrect: false }, { text: 'Corazón', isCorrect: false }, { text: 'Pulmón', isCorrect: false }, { text: 'Estómago', isCorrect: false }] },
    { text: '¿Qué gas expulsan las plantas en la fotosíntesis?', difficulty: 'EASY', explanation: 'Las plantas expulsan oxígeno (O2).', options: [{ text: 'Oxígeno', isCorrect: true }, { text: 'Dióxido de carbono', isCorrect: false }, { text: 'Nitrógeno', isCorrect: false }, { text: 'Hidrógeno', isCorrect: false }, { text: 'Monóxido de carbono', isCorrect: false }] },
    { text: '¿Qué es la selección natural?', difficulty: 'MEDIUM', explanation: 'La selección natural es la supervivencia de los más aptos.', options: [{ text: 'Supervivencia de los más aptos', isCorrect: true }, { text: 'Cambio al azar del ADN', isCorrect: false }, { text: 'Adaptación al clima', isCorrect: false }, { text: 'Evolución dirigida', isCorrect: false }, { text: 'Mutación controlada', isCorrect: false }] },
  ]},
  // UNI - Psicología
  { universityId: 'uni', subjectId: 'psicologia', questions: [
    { text: '¿Qué es la percepción?', difficulty: 'EASY', explanation: 'La percepción interpreta y organiza la información sensorial.', options: [{ text: 'Interpretación de información sensorial', isCorrect: true }, { text: 'Sensación directa', isCorrect: false }, { text: 'Memoria a largo plazo', isCorrect: false }, { text: 'Proceso de aprendizaje', isCorrect: false }, { text: 'Respuesta refleja', isCorrect: false }] },
    { text: '¿Qué es la memoria a corto plazo?', difficulty: 'MEDIUM', explanation: 'La memoria a corto plazo retiene información temporalmente (15-30 segundos).', options: [{ text: 'Retención temporal de información', isCorrect: true }, { text: 'Almacenamiento permanente', isCorrect: false }, { text: 'Memoria heredada', isCorrect: false }, { text: 'Recuerdo emocional', isCorrect: false }, { text: 'Aprendizaje kinestésico', isCorrect: false }] },
    { text: '¿Quién propuso la pirámide de necesidades humanas?', difficulty: 'EASY', explanation: 'Abraham Maslow propuso la pirámide de necesidades humanas.', options: [{ text: 'Abraham Maslow', isCorrect: true }, { text: 'Sigmund Freud', isCorrect: false }, { text: 'Carl Jung', isCorrect: false }, { text: 'B.F. Skinner', isCorrect: false }, { text: 'Jean Piaget', isCorrect: false }] },
    { text: '¿Qué es el inconsciente según Freud?', difficulty: 'MEDIUM', explanation: 'El inconsciente contiene deseos y experiencias reprimidas.', options: [{ text: 'Depósito de deseos reprimidos', isCorrect: true }, { text: 'Zona de pensamientos lógicos', isCorrect: false }, { text: 'Memoria explícita', isCorrect: false }, { text: 'Consciencia despierta', isCorrect: false }, { text: 'Intuición consciente', isCorrect: false }] },
    { text: '¿Qué es el condicionamiento clásico?', difficulty: 'MEDIUM', explanation: 'El condicionamiento clásico asocia un estímulo neutro con uno que produce respuesta automática.', options: [{ text: 'Asociación de estímulos', isCorrect: true }, { text: 'Refuerzo positivo', isCorrect: false }, { text: 'Aprendizaje por observación', isCorrect: false }, { text: 'Castigo negativo', isCorrect: false }, { text: 'Memoria episódica', isCorrect: false }] },
    { text: '¿Qué es la inteligencia emocional?', difficulty: 'MEDIUM', explanation: 'La inteligencia emocional es la capacidad de manejar emociones propias y ajenas.', options: [{ text: 'Capacidad de manejar emociones', isCorrect: true }, { text: 'Cociente intelectual alto', isCorrect: false }, { text: 'Memoria emocional', isCorrect: false }, { text: 'Sensibilidad artística', isCorrect: false }, { text: 'Empatía natural', isCorrect: false }] },
    { text: '¿Qué es el estrés postraumático?', difficulty: 'MEDIUM', explanation: 'El TEPT ocurre tras experimentar un evento traumático.', options: [{ text: 'Trastorno tras evento traumático', isCorrect: true }, { text: 'Ansiedad generalizada', isCorrect: false }, { text: 'Depresión mayor', isCorrect: false }, { text: 'Fobia simple', isCorrect: false }, { text: 'Pánico crónico', isCorrect: false }] },
    { text: '¿Qué es la personalidad?', difficulty: 'EASY', explanation: 'La personalidad son los patrones únicos de pensamientos, emociones y comportamiento.', options: [{ text: 'Patrones únicos de pensamiento y conducta', isCorrect: true }, { text: 'Comportamiento social', isCorrect: false }, { text: 'Estado emocional', isCorrect: false }, { text: 'Inteligencia general', isCorrect: false }, { text: 'Habilidades cognitivas', isCorrect: false }] },
    { text: '¿Qué área de la psicología estudia los procesos mentales básicos?', difficulty: 'HARD', explanation: 'La psicología cognitiva estudia percepción, memoria, lenguaje y resolución de problemas.', options: [{ text: 'Psicología cognitiva', isCorrect: true }, { text: 'Psicología clínica', isCorrect: false }, { text: 'Psicología social', isCorrect: false }, { text: 'Psicología educativa', isCorrect: false }, { text: 'Psicología organizacional', isCorrect: false }] },
    { text: '¿Qué es el efecto placebo?', difficulty: 'MEDIUM', explanation: 'El efecto placebo ocurre cuando un tratamiento sin efecto real produce mejora por expectativa.', options: [{ text: 'Mejora por expectativa del paciente', isCorrect: true }, { text: 'Efecto secundario de medicamentos', isCorrect: false }, { text: 'Tratamiento psicológico', isCorrect: false }, { text: 'Reacción alérgica', isCorrect: false }, { text: 'Efecto adverso', isCorrect: false }] },
  ]},
  // UNSAAC - Historia
  { universityId: 'unsaac', subjectId: 'historia', questions: [
    { text: '¿Qué imperio precedió a los incas en el Cusco?', difficulty: 'MEDIUM', explanation: 'El imperio Chimú, con capital en Chan Chan, fue uno de los principales.', options: [{ text: 'Imperio Chimú', isCorrect: true }, { text: 'Imperio Tiahuanaco', isCorrect: false }, { text: 'Reino Wari', isCorrect: false }, { text: 'Cultura Moche', isCorrect: false }, { text: 'Cultura Nazca', isCorrect: false }] },
    { text: '¿Qué significa "Tawantinsuyo"?', difficulty: 'EASY', explanation: 'Tawantinsuyo significa "las cuatro regiones".', options: [{ text: 'Las cuatro regiones', isCorrect: true }, { text: 'El imperio del sol', isCorrect: false }, { text: 'Tierra de los incas', isCorrect: false }, { text: 'Las tierras altas', isCorrect: false }, { text: 'El valle sagrado', isCorrect: false }] },
    { text: '¿En qué año se fundó el Cusco?', difficulty: 'HARD', explanation: 'Según la tradición, Manco Cápac fundó el Cusco alrededor de 1200 d.C.', options: [{ text: '1200 d.C.', isCorrect: true }, { text: '1400 d.C.', isCorrect: false }, { text: '1000 d.C.', isCorrect: false }, { text: '1500 d.C.', isCorrect: false }, { text: '1300 d.C.', isCorrect: false }] },
    { text: '¿Qué ruta usaban los incas para comunicarse?', difficulty: 'MEDIUM', explanation: 'Los chasquis corrían por el Qhapaq Ñan.', options: [{ text: 'Qhapaq Ñan (camino del inca)', isCorrect: true }, { text: 'Río Amazonas', isCorrect: false }, { text: 'Costas del Pacífico', isCorrect: false }, { text: 'Rutas fluviales', isCorrect: false }, { text: 'Caminos costeros', isCorrect: false }] },
    { text: '¿Qué爹妈神明 protegía el Cusco?', difficulty: 'HARD', explanation: 'Wiracocha era la deidad principal creadora.', options: [{ text: 'Wiracocha', isCorrect: true }, { text: 'Inti (dio del sol)', isCorrect: false }, { text: 'Pachamama', isCorrect: false }, { text: 'Mama Quilla', isCorrect: false }, { text: 'Supay', isCorrect: false }] },
    { text: '¿Qué función tenían los tambos en el Qhapaq Ñan?', difficulty: 'MEDIUM', explanation: 'Los tambos eran puntos de descanso y provisiones.', options: [{ text: 'Puntos de descanso y provisión', isCorrect: true }, { text: 'Templos religiosos', isCorrect: false }, { text: 'Centros administrativos', isCorrect: false }, { text: 'Guarniciones militares', isCorrect: false }, { text: 'Mercados comerciales', isCorrect: false }] },
    { text: '¿Quién fue el último inca?', difficulty: 'EASY', explanation: 'Atahualpa fue el último inca, capturado por Pizarro en 1533.', options: [{ text: 'Atahualpa', isCorrect: true }, { text: 'Manco Inca', isCorrect: false }, { text: 'Huayna Cápac', isCorrect: false }, { text: 'Pachacútec', isCorrect: false }, { text: 'Túpac Amaru I', isCorrect: false }] },
    { text: '¿Qué era el ayni?', difficulty: 'MEDIUM', explanation: 'El ayni era el sistema de reciprocidad mutualista entre familias andinas.', options: [{ text: 'Trabajo recíproco entre familias', isCorrect: true }, { text: 'Impuesto al inca', isCorrect: false }, { text: 'Sistema de cultivo', isCorrect: false }, { text: 'Calendario agrícola', isCorrect: false }, { text: 'Religión estatal', isCorrect: false }] },
    { text: '¿Qué era la mita?', difficulty: 'MEDIUM', explanation: 'La mita era el sistema de trabajo obligatorio para el estado inca.', options: [{ text: 'Trabajo obligatorio para el estado', isCorrect: true }, { text: 'Tributo en productos', isCorrect: false }, { text: 'Servicio militar', isCorrect: false }, { text: 'Adoración religiosa', isCorrect: false }, { text: 'Festividad andina', isCorrect: false }] },
    { text: '¿Qué cultura desarrolló los geoglifos de Nazca?', difficulty: 'EASY', explanation: 'La cultura Nazca creó los geoglifos en el desierto de Nazca.', options: [{ text: 'Cultura Nazca', isCorrect: true }, { text: 'Cultura Moche', isCorrect: false }, { text: 'Cultura Paracas', isCorrect: false }, { text: 'Cultura Wari', isCorrect: false }, { text: 'Imperio Chimú', isCorrect: false }] },
  ]},
  // UNSAAC - Geografía
  { universityId: 'unsaac', subjectId: 'geografia', questions: [
    { text: '¿Cuál es la capital del departamento del Cusco?', difficulty: 'EASY', explanation: 'Cusco es la capital del departamento del Cusco.', options: [{ text: 'Cusco', isCorrect: true }, { text: 'Arequipa', isCorrect: false }, { text: 'Puno', isCorrect: false }, { text: 'Ayacucho', isCorrect: false }, { text: 'Juliaca', isCorrect: false }] },
    { text: '¿Qué nevado se encuentra cerca del Cusco?', difficulty: 'MEDIUM', explanation: 'El nevado Salkantay (6,271 m) es uno de los más emblemáticos.', options: [{ text: 'Salkantay', isCorrect: true }, { text: 'Huascarán', isCorrect: false }, { text: 'Coropuna', isCorrect: false }, { text: 'Ausangate', isCorrect: false }, { text: 'Yerupajá', isCorrect: false }] },
    { text: '¿Qué río atraviesa el valle del Cusco?', difficulty: 'MEDIUM', explanation: 'El río Vilcanota (también llamado Urubamba) atraviesa el valle.', options: [{ text: 'Río Vilcanota/Urubamba', isCorrect: true }, { text: 'Río Apurímac', isCorrect: false }, { text: 'Río Mantaro', isCorrect: false }, { text: 'Río Ucayali', isCorrect: false }, { text: 'Río Marañón', isCorrect: false }] },
    { text: '¿Qué reserva natural protege el oso andino?', difficulty: 'HARD', explanation: 'La Reserva Paisajística de Choquequirao protege el hábitat del oso andino.', options: [{ text: 'Reserva de Choquequirao', isCorrect: true }, { text: 'Parque Nacional del Río Abiseo', isCorrect: false }, { text: 'Reserva del Manú', isCorrect: false }, { text: 'Santuario de Machu Picchu', isCorrect: false }, { text: 'Parque Nacional del Cotahuasi', isCorrect: false }] },
    { text: '¿Qué clima predomina en la ciudad del Cusco?', difficulty: 'EASY', explanation: 'Cusco tiene clima templado subtropical.', options: [{ text: 'Templado subtropical', isCorrect: true }, { text: 'Tropical lluvioso', isCorrect: false }, { text: 'Desértico', isCorrect: false }, { text: 'Polar', isCorrect: false }, { text: 'Semiárido', isCorrect: false }] },
    { text: '¿A qué altitud está Machu Picchu?', difficulty: 'EASY', explanation: 'Machu Picchu está a aproximadamente 2,430 m.s.n.m.', options: [{ text: '2,430 m.s.n.m.', isCorrect: true }, { text: '3,000 m.s.n.m.', isCorrect: false }, { text: '1,500 m.s.n.m.', isCorrect: false }, { text: '4,000 m.s.n.m.', isCorrect: false }, { text: '3,500 m.s.n.m.', isCorrect: false }] },
    { text: '¿Qué bioma caracteriza a la sierra del Cusco?', difficulty: 'MEDIUM', explanation: 'El bioma de puna andina caracteriza las tierras altas.', options: [{ text: 'Puna andina', isCorrect: true }, { text: 'Selva tropical', isCorrect: false }, { text: 'Bosque nublado', isCorrect: false }, { text: 'Desierto costero', isCorrect: false }, { text: 'Sabana', isCorrect: false }] },
    { text: '¿Qué lago se encuentra cerca del Cusco?', difficulty: 'EASY', explanation: 'El lago Piurita se encuentra cerca del Cusco.', options: [{ text: 'Lago Piurita', isCorrect: true }, { text: 'Lago Titicaca', isCorrect: false }, { text: 'Lago Junín', isCorrect: false }, { text: 'Lago Rimac', isCorrect: false }, { text: 'Lago Amazonía', isCorrect: false }] },
    { text: '¿Qué ecosistema alberga la Reserva del Manú?', difficulty: 'MEDIUM', explanation: 'La Reserva del Manú protege uno de los ecosistemas de mayor biodiversidad.', options: [{ text: 'Selva tropical amazónica', isCorrect: true }, { text: 'Puna andina', isCorrect: false }, { text: 'Bosque nublado', isCorrect: false }, { text: 'Desierto altoandino', isCorrect: false }, { text: 'Matorral andino', isCorrect: false }] },
    { text: '¿Cuántas regiones naturales tiene el Perú según Pulgar Vidal?', difficulty: 'EASY', explanation: 'Javier Pulgar Vidal identificó 8 regiones naturales.', options: [{ text: '8 regiones', isCorrect: true }, { text: '3 regiones', isCorrect: false }, { text: '5 regiones', isCorrect: false }, { text: '4 regiones', isCorrect: false }, { text: '6 regiones', isCorrect: false }] },
  ]},
  // UNSAAC - Economía
  { universityId: 'unsaac', subjectId: 'economia', questions: [
    { text: '¿Qué sector económico predomina en Cusco?', difficulty: 'MEDIUM', explanation: 'El turismo es el sector económico más importante del Cusco.', options: [{ text: 'Turismo', isCorrect: true }, { text: 'Minería', isCorrect: false }, { text: 'Agricultura', isCorrect: false }, { text: 'Industria', isCorrect: false }, { text: 'Pesca', isCorrect: false }] },
    { text: '¿Qué es el PEA?', difficulty: 'MEDIUM', explanation: 'La Población Económicamente Activa es la que trabaja o busca trabajo.', options: [{ text: 'Población Económicamente Activa', isCorrect: true }, { text: 'Población Empleada Activa', isCorrect: false }, { text: 'Población Económica Anual', isCorrect: false }, { text: 'Producto Económico Activo', isCorrect: false }, { text: 'Plan Económico de Ayuda', isCorrect: false }] },
    { text: '¿Qué es el producto bruto interno per cápita?', difficulty: 'MEDIUM', explanation: 'Es el PBI dividido entre la población total.', options: [{ text: 'PBI dividido por población', isCorrect: true }, { text: 'PBI más población', isCorrect: false }, { text: 'PBI menos exportaciones', isCorrect: false }, { text: 'PBI menos deudas', isCorrect: false }, { text: 'PBI más inversiones', isCorrect: false }] },
    { text: '¿Qué significa exportar?', difficulty: 'EASY', explanation: 'Exportar es vender productos o servicios a otros países.', options: [{ text: 'Vender productos al exterior', isCorrect: true }, { text: 'Comprar productos del exterior', isCorrect: false }, { text: 'Producir para el mercado local', isCorrect: false }, { text: 'Crear una empresa', isCorrect: false }, { text: 'Invertir en bolsa', isCorrect: false }] },
    { text: '¿Qué es la BCP?', difficulty: 'EASY', explanation: 'BCP es el Banco de Crédito del Perú.', options: [{ text: 'Banco de Crédito del Perú', isCorrect: true }, { text: 'Banco Central del Perú', isCorrect: false }, { text: 'Bolsa de Valores de Lima', isCorrect: false }, { text: 'Bono Civil Peruano', isCorrect: false }, { text: 'Cooperativa Popular', isCorrect: false }] },
    { text: '¿Qué es la tasa de desempleo?', difficulty: 'EASY', explanation: 'La tasa de desempleo mide el porcentaje de PEA sin empleo.', options: [{ text: 'Porcentaje de PEA sin empleo', isCorrect: true }, { text: 'Número de empleos totales', isCorrect: false }, { text: 'Salario mínimo', isCorrect: false }, { text: 'Población inactiva', isCorrect: false }, { text: 'Empleadores formales', isCorrect: false }] },
    { text: '¿Qué producto es típico de exportación del Cusco?', difficulty: 'MEDIUM', explanation: 'Las artesanías y textilería tradicionales son exportaciones culturales.', options: [{ text: 'Artesanías y textiles', isCorrect: true }, { text: 'Cobre', isCorrect: false }, { text: 'Petróleo', isCorrect: false }, { text: 'Ganado vacuno', isCorrect: false }, { text: 'Trigo', isCorrect: false }] },
    { text: '¿Qué es la inversión extranjera?', difficulty: 'EASY', explanation: 'La inversión extranjera es cuando alguien de otro país invierte en el Perú.', options: [{ text: 'Capital del exterior invertido en el país', isCorrect: true }, { text: 'Dinero nacional invertido afuera', isCorrect: false }, { text: 'Préstamo del gobierno', isCorrect: false }, { text: 'Impuesto a empresas', isCorrect: false }, { text: 'Ahorro nacional', isCorrect: false }] },
    { text: '¿Qué es el mercado interno?', difficulty: 'EASY', explanation: 'El mercado interno es el conjunto de transacciones económicas dentro de un país.', options: [{ text: 'Transacciones económicas dentro del país', isCorrect: true }, { text: 'Comercio con otros países', isCorrect: false }, { text: 'Bolsa de valores nacional', isCorrect: false }, { text: 'Exportaciones totales', isCorrect: false }, { text: 'Deuda externa', isCorrect: false }] },
    { text: '¿Qué significa diversificar la economía?', difficulty: 'MEDIUM', explanation: 'Diversificar es desarrollar múltiples sectores para no depender de uno solo.', options: [{ text: 'Desarrollar múltiples sectores', isCorrect: true }, { text: 'Concentrar todo en un sector', isCorrect: false }, { text: 'Eliminar el comercio', isCorrect: false }, { text: 'Cerrar fronteras', isCorrect: false }, { text: 'Reducir impuestos', isCorrect: false }] },
  ]},
  // UNSAAC - Filosofía
  { universityId: 'unsaac', subjectId: 'filosofia', questions: [
    { text: '¿Qué es la ética aristotélica?', difficulty: 'MEDIUM', explanation: 'Para Aristóteles, la ética busca la eudaimonía (felicidad) mediante la virtud.', options: [{ text: 'Búsqueda de la felicidad mediante la virtud', isCorrect: true }, { text: 'Placer como máximo bien', isCorrect: false }, { text: 'Deber moral abstracto', isCorrect: false }, { text: 'Libertad absoluta', isCorrect: false }, { text: 'Conocimiento del bien', isCorrect: false }] },
    { text: '¿Qué es el relativismo moral?', difficulty: 'MEDIUM', explanation: 'El relativismo moral sostiene que los valores morales dependen de cada cultura.', options: [{ text: 'Valores morales dependen de la cultura', isCorrect: true }, { text: 'Existen valores universales', isCorrect: false }, { text: 'La moral es innata', isCorrect: false }, { text: 'Todo es relativo al dinero', isCorrect: false }, { text: 'Los valores son fijos', isCorrect: false }] },
    { text: '¿Qué propuso Hobbes sobre el estado natural?', difficulty: 'HARD', explanation: 'Hobbes describió el estado natural como "guerra de todos contra todos".', options: [{ text: 'Guerra de todos contra todos', isCorrect: true }, { text: 'Paraíso terrenal', isCorrect: false }, { text: 'Armonía natural', isCorrect: false }, { text: 'Libertad absoluta', isCorrect: false }, { text: 'Cooperación natural', isCorrect: false }] },
    { text: '¿Qué es el empirismo?', difficulty: 'MEDIUM', explanation: 'El empirismo sostiene que todo conocimiento proviene de la experiencia sensorial.', options: [{ text: 'Conocimiento源于 experiencia', isCorrect: true }, { text: 'Conocimiento innato', isCorrect: false }, { text: 'Razón pura', isCorrect: false }, { text: 'Revelación divina', isCorrect: false }, { text: 'Intuición', isCorrect: false }] },
    { text: '¿Qué filósofo dijo "el hombre es un lobo para el hombre"?', difficulty: 'HARD', explanation: 'Plauto escribió esta frase que Hobbes popularizó.', options: [{ text: 'Thomas Hobbes', isCorrect: true }, { text: 'John Locke', isCorrect: false }, { text: 'Jean-Jacques Rousseau', isCorrect: false }, { text: 'Platón', isCorrect: false }, { text: 'Aristóteles', isCorrect: false }] },
    { text: '¿Qué es el racionalismo?', difficulty: 'MEDIUM', explanation: 'El racionalismo sostiene que la razón es la fuente principal del conocimiento.', options: [{ text: 'La razón como fuente del conocimiento', isCorrect: true }, { text: 'La experiencia como fuente', isCorrect: false }, { text: 'La emoción como guía', isCorrect: false }, { text: 'La tradición como guía', isCorrect: false }, { text: 'La fe como fuente', isCorrect: false }] },
    { text: '¿Qué es la metafísica?', difficulty: 'EASY', explanation: 'La metafísica estudia la naturaleza de la realidad.', options: [{ text: 'Estudio de la naturaleza de la realidad', isCorrect: true }, { text: 'Estudio de la lógica', isCorrect: false }, { text: 'Estudio de la moral', isCorrect: false }, { text: 'Estudio de la estética', isCorrect: false }, { text: 'Estudio del lenguaje', isCorrect: false }] },
    { text: '¿Qué es el estoicismo?', difficulty: 'MEDIUM', explanation: 'El estoicismo enseña la virtud moral y la serenidad ante las adversidades.', options: [{ text: 'Virtud y serenidad ante el destino', isCorrect: true }, { text: 'Búsqueda del placer', isCorrect: false }, { text: 'Ascetismo extremo', isCorrect: false }, { text: 'Relativismo moral', isCorrect: false }, { text: 'Egoísmo racional', isCorrect: false }] },
    { text: '¿Qué es el contractualismo?', difficulty: 'MEDIUM', explanation: 'El contractualismo propone que la legitimidad política viene de un acuerdo entre ciudadanos.', options: [{ text: 'Acuerdo entre ciudadanos para convivencia', isCorrect: true }, { text: 'Gobierno divino de los reyes', isCorrect: false }, { text: 'Dominación del más fuerte', isCorrect: false }, { text: 'Libertad natural sin gobierno', isCorrect: false }, { text: 'Tradición como legitimidad', isCorrect: false }] },
    { text: '¿Qué propuso John Locke sobre los derechos naturales?', difficulty: 'HARD', explanation: 'Locke propuso que todos tienen derechos a la vida, libertad y propiedad.', options: [{ text: 'Vida, libertad y propiedad', isCorrect: true }, { text: 'Solo vida', isCorrect: false }, { text: 'Libertad absoluta', isCorrect: false }, { text: 'Seguridad y orden', isCorrect: false }, { text: 'Igualdad total', isCorrect: false }] },
  ]},
  // UNSAAC - Biología
  { universityId: 'unsaac', subjectId: 'biologia', questions: [
    { text: '¿Qué animal del Cusco está amenazado de extinción?', difficulty: 'HARD', explanation: 'El oso andino (Tremarctos ornatus) es una especie amenazada.', options: [{ text: 'Oso andino (Tremarctos ornatus)', isCorrect: true }, { text: 'Condor andino', isCorrect: false }, { text: 'Vicuña', isCorrect: false }, { text: 'Lobo de tierra', isCorrect: false }, { text: 'Puma', isCorrect: false }] },
    { text: '¿Qué tipo de bosque se encuentra en la ceja de selva del Cusco?', difficulty: 'MEDIUM', explanation: 'El bosque nublado caracteriza la ceja de selva.', options: [{ text: 'Bosque nublado', isCorrect: true }, { text: 'Selva baja tropical', isCorrect: false }, { text: 'Puna', isCorrect: false }, { text: 'Desierto', isCorrect: false }, { text: 'Matorral xerófilo', isCorrect: false }] },
    { text: '¿Qué es la fotosíntesis?', difficulty: 'EASY', explanation: 'La fotosíntesis convierte luz solar en glucosa.', options: [{ text: 'Conversión de luz en glucosa', isCorrect: true }, { text: 'Respiración vegetal', isCorrect: false }, { text: 'Absorción de agua', isCorrect: false }, { text: 'Crecimiento celular', isCorrect: false }, { text: 'Reproducción asexual', isCorrect: false }] },
    { text: '¿Qué órgano de la planta realiza la fotosíntesis?', difficulty: 'EASY', explanation: 'Las hojas son los órganos principales de la fotosíntesis.', options: [{ text: 'Hojas', isCorrect: true }, { text: 'Raíz', isCorrect: false }, { text: 'Tallo', isCorrect: false }, { text: 'Flor', isCorrect: false }, { text: 'Semilla', isCorrect: false }] },
    { text: '¿Qué es la adaptación biológica?', difficulty: 'MEDIUM', explanation: 'La adaptación biológica es el proceso por el cual los organismos se ajustan a su entorno.', options: [{ text: 'Ajuste de organismos al entorno', isCorrect: true }, { text: 'Cambio de especie', isCorrect: false }, { text: 'Extinción', isCorrect: false }, { text: 'Reproducción', isCorrect: false }, { text: 'Mutación al azar', isCorrect: false }] },
    { text: '¿Qué es un ecosistema?', difficulty: 'EASY', explanation: 'Un ecosistema es el conjunto de organismos y su ambiente físico en interacción.', options: [{ text: 'Organismos + ambiente físico en interacción', isCorrect: true }, { text: 'Un solo organismo', isCorrect: false }, { text: 'Un bioma completo', isCorrect: false }, { text: 'Una población animal', isCorrect: false }, { text: 'Un hábitat específico', isCorrect: false }] },
    { text: '¿Qué es la cadena alimenticia?', difficulty: 'EASY', explanation: 'La cadena alimenticia muestra cómo la energía fluye de un organismo a otro.', options: [{ text: 'Flujo de energía entre organismos', isCorrect: true }, { text: 'Lista de animales', isCorrect: false }, { text: 'Red de computadoras', isCorrect: false }, { text: 'Crecimiento de plantas', isCorrect: false }, { text: 'Reproducción de especies', isCorrect: false }] },
    { text: '¿Qué es el cambio climático?', difficulty: 'EASY', explanation: 'El cambio climático es la alteración del clima global por actividades humanas.', options: [{ text: 'Alteración del clima por actividad humana', isCorrect: true }, { text: 'Cambio natural de estaciones', isCorrect: false }, { text: 'Variación local del clima', isCorrect: false }, { text: 'Aumento de temperatura solar', isCorrect: false }, { text: 'Enfriamiento global', isCorrect: false }] },
    { text: '¿Qué es la biodiversidad?', difficulty: 'EASY', explanation: 'La biodiversidad es la variedad de vida en un ecosistema.', options: [{ text: 'Variedad de vida en un ecosistema', isCorrect: true }, { text: 'Cantidad de una sola especie', isCorrect: false }, { text: 'Número de ecosistemas', isCorrect: false }, { text: 'Población total', isCorrect: false }, { text: 'Extinción de especies', isCorrect: false }] },
    { text: '¿Qué es la respiración celular?', difficulty: 'MEDIUM', explanation: 'La respiración celular es el proceso que genera energía a partir de glucosa.', options: [{ text: 'Generación de energía desde glucosa', isCorrect: true }, { text: 'Absorción de oxígeno por los pulmones', isCorrect: false }, { text: 'Exhalación de CO2', isCorrect: false }, { text: 'Proceso de las plantas', isCorrect: false }, { text: 'Síntesis de proteínas', isCorrect: false }] },
  ]},
  // UNSAAC - Psicología
  { universityId: 'unsaac', subjectId: 'psicologia', questions: [
    { text: '¿Qué es el aprendizaje?', difficulty: 'EASY', explanation: 'El aprendizaje es el proceso de adquirir nuevos conocimientos o habilidades.', options: [{ text: 'Adquisición de nuevos conocimientos/habilidades', isCorrect: true }, { text: 'Memoria a largo plazo', isCorrect: false }, { text: 'Reflejo automático', isCorrect: false }, { text: 'Instinto', isCorrect: false }, { text: 'Herencia genética', isCorrect: false }] },
    { text: '¿Qué es la memoria?', difficulty: 'EASY', explanation: 'La memoria es la capacidad del cerebro para almacenar y recuperar información.', options: [{ text: 'Almacenamiento y recuperación de información', isCorrect: true }, { text: 'Pensamiento lógico', isCorrect: false }, { text: 'Percepción sensorial', isCorrect: false }, { text: 'Emoción intensa', isCorrect: false }, { text: 'Comportamiento observable', isCorrect: false }] },
    { text: '¿Qué es la motivación?', difficulty: 'MEDIUM', explanation: 'La motivación es el conjunto de factores que dirigen y sostienen la conducta.', options: [{ text: 'Factores que dirigen y sostienen la conducta', isCorrect: true }, { text: 'Emoción pasajera', isCorrect: false }, { text: 'Reflejo innato', isCorrect: false }, { text: 'Memoria emocional', isCorrect: false }, { text: 'Percepción del entorno', isCorrect: false }] },
    { text: '¿Qué es la frustración?', difficulty: 'EASY', explanation: 'La frustración es la emoción que surge cuando un deseo o meta no se puede alcanzar.', options: [{ text: 'Emoción por meta no alcanzada', isCorrect: true }, { text: 'Alegría extrema', isCorrect: false }, { text: 'Miedo al éxito', isCorrect: false }, { text: 'Tristeza constante', isCorrect: false }, { text: 'Enojo sin causa', isCorrect: false }] },
    { text: '¿Qué método usaban los conductistas para estudiar el aprendizaje?', difficulty: 'HARD', explanation: 'Los conductistas como Skinner usaban el condicionamiento operante.', options: [{ text: 'Condicionamiento operante', isCorrect: true }, { text: 'Introspección', isCorrect: false }, { text: 'Entrevistas clínicas', isCorrect: false }, { text: 'Pruebas de inteligencia', isCorrect: false }, { text: 'Observación naturalista', isCorrect: false }] },
    { text: '¿Qué es la autoestima?', difficulty: 'EASY', explanation: 'La autoestima es la valoración que una persona tiene de sí misma.', options: [{ text: 'Valoración de sí mismo', isCorrect: true }, { text: 'Conocimiento personal', isCorrect: false }, { text: 'Memoria de uno mismo', isCorrect: false }, { text: 'Identidad social', isCorrect: false }, { text: 'Personalidad', isCorrect: false }] },
    { text: '¿Qué es el estrés?', difficulty: 'EASY', explanation: 'El estrés es la respuesta del cuerpo a demandas o amenazas del entorno.', options: [{ text: 'Respuesta a demandas o amenazas', isCorrect: true }, { text: 'Estado de relajación', isCorrect: false }, { text: 'Emoción positiva', isCorrect: false }, { text: 'Proceso de aprendizaje', isCorrect: false }, { text: 'Tipo de memoria', isCorrect: false }] },
    { text: '¿Qué es la cognición?', difficulty: 'MEDIUM', explanation: 'La cognición incluye todos los procesos mentales: percepción, memoria, razonamiento.', options: [{ text: 'Procesos mentales en general', isCorrect: true }, { text: 'Solo la memoria', isCorrect: false }, { text: 'Solo las emociones', isCorrect: false }, { text: 'Solo el comportamiento', isCorrect: false }, { text: 'Solo la percepción', isCorrect: false }] },
    { text: '¿Qué es el desarrollo humano?', difficulty: 'EASY', explanation: 'El desarrollo humano estudia los cambios físicos, cognitivos y sociales a lo largo de la vida.', options: [{ text: 'Cambios físicos, cognitivos y sociales', isCorrect: true }, { text: 'Solo crecimiento físico', isCorrect: false }, { text: 'Solo el envejecimiento', isCorrect: false }, { text: 'Solo la madurez', isCorrect: false }, { text: 'Solo la infancia', isCorrect: false }] },
    { text: '¿Qué es la empatía?', difficulty: 'EASY', explanation: 'La empatía es la capacidad de comprender y compartir los sentimientos de otro.', options: [{ text: 'Comprender y compartir sentimientos ajenos', isCorrect: true }, { text: 'Sentir pena por otro', isCorrect: false }, { text: 'Identificarse con otro', isCorrect: false }, { text: 'Sentir envidia', isCorrect: false }, { text: 'Preocupación por uno mismo', isCorrect: false }] },
  ]},
  // UNSAAC - Química (agregar faltante)
  { universityId: 'unsaac', subjectId: 'quimica', questions: [
    { text: '¿Qué es un átomo?', difficulty: 'EASY', explanation: 'Un átomo es la unidad más pequeña de la materia.', options: [{ text: 'Unidad más pequeña de la materia', isCorrect: true }, { text: 'Una molécula pequeña', isCorrect: false }, { text: 'Un electrón', isCorrect: false }, { text: 'Un protón', isCorrect: false }, { text: 'Una célula', isCorrect: false }] },
    { text: '¿Qué es la tabla periódica?', difficulty: 'EASY', explanation: 'La tabla periódica organiza los elementos químicos por sus propiedades.', options: [{ text: 'Organización de elementos por propiedades', isCorrect: true }, { text: 'Lista de medicamentos', isCorrect: false }, { text: 'Tabla de elementos biológicos', isCorrect: false }, { text: 'Registro de átomos', isCorrect: false }, { text: 'Clasificación de moléculas', isCorrect: false }] },
    { text: '¿Qué es un enlace covalente?', difficulty: 'MEDIUM', explanation: 'Un enlace covalente se forma cuando dos átomos comparten electrones.', options: [{ text: 'Compartición de electrones entre átomos', isCorrect: true }, { text: 'Transferencia de electrones', isCorrect: false }, { text: 'Attractie entre iones', isCorrect: false }, { text: 'Enlace metálico', isCorrect: false }, { text: 'Fuerza nuclear', isCorrect: false }] },
    { text: '¿Qué es el número atómico?', difficulty: 'EASY', explanation: 'El número atómico es el número de protones en el núcleo de un átomo.', options: [{ text: 'Número de protones', isCorrect: true }, { text: 'Número de electrones', isCorrect: false }, { text: 'Peso molecular', isCorrect: false }, { text: 'Número de neutrones', isCorrect: false }, { text: 'Masa atómica', isCorrect: false }] },
    { text: '¿Qué es una reacción química?', difficulty: 'EASY', explanation: 'Una reacción química es un proceso donde sustancias se transforman en otras.', options: [{ text: 'Transformación de sustancias en otras', isCorrect: true }, { text: 'Mezcla de sustancias', isCorrect: false }, { text: 'Cambio de estado', isCorrect: false }, { text: 'Disolución', isCorrect: false }, { text: 'Evaporación', isCorrect: false }] },
    { text: '¿Qué es el pH?', difficulty: 'MEDIUM', explanation: 'El pH mide la acidez o alcalinidad de una solución.', options: [{ text: 'Medida de acidez/alcalinidad', isCorrect: true }, { text: 'Cantidad de agua', isCorrect: false }, { text: 'Temperatura química', isCorrect: false }, { text: 'Concentración de sales', isCorrect: false }, { text: 'Densidad del líquido', isCorrect: false }] },
    { text: '¿Qué es un mol?', difficulty: 'HARD', explanation: 'Un mol es la cantidad de sustancia que contiene 6.022×10²³ entidades.', options: [{ text: '6.022×10²³ entidades', isCorrect: true }, { text: 'Un gramo de sustancia', isCorrect: false }, { text: 'Un litro de gas', isCorrect: false }, { text: 'Una molécula', isCorrect: false }, { text: 'Un átomo', isCorrect: false }] },
    { text: '¿Qué tipo de enlace tiene el agua (H2O)?', difficulty: 'MEDIUM', explanation: 'El agua tiene enlaces covalentes entre el oxígeno y los hidrógenos.', options: [{ text: 'Covalente', isCorrect: true }, { text: 'Iónico', isCorrect: false }, { text: 'Metálico', isCorrect: false }, { text: 'De hidrógeno', isCorrect: false }, { text: 'Van der Waals', isCorrect: false }] },
    { text: '¿Qué es la oxidación?', difficulty: 'EASY', explanation: 'La oxidación es la pérdida de electrones de una sustancia.', options: [{ text: 'Pérdida de electrones', isCorrect: true }, { text: 'Ganancia de electrones', isCorrect: false }, { text: 'Mezcla con oxígeno', isCorrect: false }, { text: 'Reacción con agua', isCorrect: false }, { text: 'Descomposición', isCorrect: false }] },
    { text: '¿Qué son los isótopos?', difficulty: 'MEDIUM', explanation: 'Los isótopos son átomos del mismo elemento con diferente número de neutrones.', options: [{ text: 'Átomos con diferente número de neutrones', isCorrect: true }, { text: 'Átomos con diferente número de protones', isCorrect: false }, { text: 'Moléculas diferentes', isCorrect: false }, { text: 'Elementos diferentes', isCorrect: false }, { text: 'Iones distintos', isCorrect: false }] },
  ]},
];

async function main() {
  console.log('Iniciando seed de preguntas ficticias...\n');

  let totalQuestions = 0;
  let skipped = 0;

  for (const uniSubject of FICTIONAL_QUESTIONS) {
    const existing = await prisma.question.count({
      where: { universityId: uniSubject.universityId, subjectId: uniSubject.subjectId },
    });

    if (existing > 0) {
      console.log(`Ya existe ${existing} preguntas para ${uniSubject.universityId} x ${uniSubject.subjectId}, saltando`);
      skipped++;
      continue;
    }

    for (const q of uniSubject.questions) {
      await prisma.question.create({
        data: {
          universityId: uniSubject.universityId,
          subjectId: uniSubject.subjectId,
          careerId: uniSubject.careerId || null,
          text: q.text,
          difficulty: q.difficulty,
          examYear: 2024,
          examPeriod: 'FICTIONAL',
          explanation: q.explanation,
          isActive: true,
          options: {
            create: q.options.map((o, idx) => ({
              text: o.text,
              isCorrect: o.isCorrect,
              orderIndex: idx,
            })),
          },
        },
      });
      totalQuestions++;
    }
    console.log(`+${uniSubject.questions.length} preguntas: ${uniSubject.universityId} x ${uniSubject.subjectId}`);
  }

  console.log(`\nResumen: ${totalQuestions} preguntas creadas, ${skipped} combinaciones saltadas`);
  console.log(`Total en DB: ${await prisma.question.count()}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());